### ISSUE TITLE
Stats_script : améliorations finales

### ISSUE THREAD

**Issue by yhamoudi** [ilsordo/SAT-SMT-Solver#14]
J'ai commencé à regarder les résultats obtenus et quelques améliorations me semblent nécessaires (si on les fait vite, je peut relancer l'ensemble des tests déjà faits).

Indispensables (?) :
-  ~~Avec les tests obtenus jusqu'à maintenant, c'est difficile de dire si les différences de temps entre heuristiques sont dues à la pertinence des heuristiques ou bien si certaines heuristiques perdent trop de temps à parcourir les clauses/variables. Il faut ajouter un timer qui indique le temps passé à choisir des littéraux pour parier (Choosing).~~
-  ~~sur select_data, il faudrait avoir un peu plus de liberté sur la construction des graphes~~
  - ~~en ordonnée : temps(global) ou temps(choosing) ou (temps(global)-temps(choosing))~~
  - ~~en abscisse : n ou l ou k~~
  - ~~sur les courbes en elles-mêmes : n ou l ou k (par exemple, on fixe l, on met k en abscisse, temps(global) en ordonnée et différentes courbes étiquetées par k~~
- pour tseitin et color. On a plusieurs possibilités : 
  - je peux faire des bash (mais ça sera à "l'ancienne", sans les avantages de ruby (multithreading, bdd facilement manipulable)...)
  - on peut intégrer la gestion de color et tseitin dans les scripts actuels (ça peut faire pas mal de travail)
  - on peut dupliquer le code actuel de base.rb en deux versions tseitin et color. On aurait alors 3 versions indépendantes avec beaucoup de code dupliqué. C'est pas le plus propre mais c'est peut-être le plus rapide à mettre en place.

En bonus : 
- dans les scripts actuels, on génère une cnf pour chaque (algo,heur,n,l,k). Par exemple, avec sample=2 et (wl,[dlis,wl],100,3,400), il y a actuellement 4 cnf générées. Ça serait mieux si on gardait une même cnf pour l'ensemble des tests. Dans le cas précédent, on ne générerait que 2 cnf que l'on enverrait sur les deux heuristiques.
- pour construire all2.db, je trouvait bizarre que le script mette autant de temps (ça m'a pris 10h) alors que les tests sont simples (moins de 10s d'après les données récupérées). En fait, je me suis rendu compte à posteriori que générer une cnf (3000,1000,10000) prenait 100s ! D'où l'intérêt de limiter le nombre de cnf générées (cf point 1 ci-dessus).

Dans le wiki (https://github.com/nagaaym/projet2/wiki/M%C3%A9thodologie-pour-les-tests), je met à jour des infos sur les tests (tests choisis/passés, comment les interpréter...).

**Comment by ilsordo** [comment]
- select_data demande maintenant à ce qu'on retourne un triplet [série,paramètre,valeur]. Avant la série c'était par défaut algo+heuristique, maintenant c'est ce qu'on veut.
- run_test avec sample = k génère une cnf et applique l'algo k fois (Je ne sais pas si c'est ce que tu voulais mais sinon il faut réécrire une fonction qui ressemble à run_tests et qui prend une liste d'algos et d'heuristiques.
- Je réfléchis pour mettre tseitin et graphes dans base.rb . Je pense qu'il suffit de créer des nouvelles classes de problèmes. Si ça ne marche pas on se contentera de bash.

**Comment by yhamoudi** [comment]
- Je n'ai pas réussi à trouver la commande à entrer pour faire la chose suivante : k en abscisse, le temps en ordonnée et 3 courbes (1 par valeur de n). J'ai essayé : select_data([100,200,300],3,"wl","dlis") { |p,r| [p.n,p.k,r.result.timers["Time (s)"]/r.count]}
- tu appliques un même algo k fois sur la même cnf ? Du coup on a k fois le même temps ? Je pensais plutôt à : on fait k fois la chose suivante : générer une cnf et l'envoyer sur tous les algos
- est-ce que tu gères le timer "Choosing" (avec possibilité de choisir en abscisse un des 3 temps parmi ceux évoqués au-dessus ?)

**Comment by yhamoudi** [comment]
j'ai l'impression que le timeout est bloqué à 0 maintenant, je pense qu'il y a un pb dans gen

**Comment by ilsordo** [comment]
Pour avoir une cnf indépendante de l'algo il faut que je réécrive pas mal
de code, j'essaierai demain.

J'ai corrigé un truc dans base.rb, ton filtre devrait marcher.

Choosing devrait être géré, vérifie en affichant le résultat d'une instance.

2014-04-04 23:07 GMT+02:00 yhamoudi notifications@github.com:

**Comment by yhamoudi** [comment]
ok, du coup tu as bien enlevé ta modif précédente (avec utilisation de la même cnf k fois sur le même algo) ?

pas contre j'ai l'impression qu'il y a un nouveau bug. Je n'arrive pas à lancer debug (tu as essayé de corriger le pb de timeout ?)

**Comment by yhamoudi** [comment]
Select_data fonctionne, c'est super ! 
Si je fais l = select_data(80,3,nil,nil,nil,4) { |p,r|  ["#{p.algo}+#{p.heuristic}",p.k,(r.result.timers["Time (s)"]-r.result.timers["Choosing (s)"])/r.count] } j'aurais bien en ordonnée la différence entre les 2 temps ?

**Comment by ilsordo** [comment]
Normalement oui.

J'ai corrigé ce qui faisait planter debug. On est comme avant sur la
signification de sample. J'essaierai de l'amélioré en même temps que
j'ajoute tseitin et color.

2014-04-04 23:58 GMT+02:00 yhamoudi notifications@github.com:

**Comment by yhamoudi** [comment]
J'ai joué un peu avec les ordonnées/abscisses/courbes (c'est vraiment puissant !) et il y a un comportement étrange : pourquoi lorsque j'entre l = select_data(100,4,nil,"wl","dlis") { |p,r|  ["#{p.algo}+#{p.heuristic}",p.k,r.result.sat] } j'ai bien la proportion (0<=..<=1) de formules satisfiables en fonction de k (alors que je pensais qu'il fallait indiquer r.result.sat/r.count) ?

**Comment by ilsordo** [comment]
Dans le cas où tu as un unique résultat par problème il moyenne par rapport
au paramètre. Si ce n'est pas le cas c'est étrange.

2014-04-05 0:41 GMT+02:00 yhamoudi notifications@github.com:

**Comment by yhamoudi** [comment]
C'est-à-dire un unique résultat ? r.count=1 ?

**Comment by ilsordo** [comment]
Oui, sinon c'est étrange.

**Comment by yhamoudi** [comment]
essaye ça : 
- charger phase.db (dans  stats_databases) qui contient : 
  - algos = ["dpll"]
  - h = ["jewa"]
  - n = 80
  - l = [3,4,5]
  - k = (1..30).map {|x| 50*x}
  - sample = 2 (*4)
  - timeout = 600
  - entrer l = select_data(80,3,nil,"wl","dlis") { |p,r| ["#{p.algo}+#{p.heuristic}",p.k,r.result.sat] } 
- il n'y a eu aucun timeout donc r.count=8 (on peut le vérifier au moment du chargement de phase.db). De plus, le nombre de cnf satisfiable a été enregistré de manière correcte (on le voit aussi  au chargement de phase.db).
- du coup, avec r.result.sat en ordonnée on s'attend à avoir un nombre entre 0 et 8. En pratique :      
  - on a la proportion de formules satisfiables (nb de cnf sat / 8). 
  - Si on fait r.result.sat \* r.count, on retrouve alors en ordonnée le nombre de cnf satisfiables (0<=..<=8)

**Comment by ilsordo** [comment]
Effectivement on moyenne complètement, je ne sais pas quand je l'ai mis
mais je n'en avais aucun souvenir ...

Du coup on peut le laisser non?

2014-04-05 12:50 GMT+02:00 yhamoudi notifications@github.com:

**Comment by yhamoudi** [comment]
~~tu es sur que la gestion de sample est comme avant ? j'ai l'impression qu'il y a sample fois la même cnf envoyée sur chaque algo. En particulier, la ligne "temp = Tempfile.open("sat")" et l'utilisation que tu fais de temp dans la suite de gen me font douter~~ j'ai rien dit

**Comment by ilsordo** [comment]
Je crois oui, dans run_test on fait p.gen à chaque fois. Après peut être
que les paramètres n l k influent fortement sur la probabilité que la
formule soit satisfiable.

2014-04-05 14:06 GMT+02:00 yhamoudi notifications@github.com:

**Comment by yhamoudi** [comment]
tu t'en sort avec les scripts :) ? 

Je devrai finir la série 2 des tests (décrite dans le wiki) d'ici demain soir. Je peux me charger d'analyser les résultats (small_length.db devrait être dispo très bientôt et c'est le test le plus intéressant). J'ai indiqué quelques critères dans le wiki qui me semblent intéressant à regarder (le temps "Choosing" (renommé maintenant en "Decision (heuristic)") est très instructif). Si tu as d'autres idées n'hésite pas à les ajouter.

Il reste tseitin et color. Je pense qu'il faut lancer les tests sur ton ordi pour les avoir rapidement (ou au moins un calibrage sur les intervalles de test réalistes). On s'y prend comment ?

**Comment by ilsordo** [comment]
Je suis un peu en galère, il faut que je réécrive une grosse partie du code et les nouvelles bases de données ne seront pas compatible avec les anciennes mais on gagne encore un peu en liberté.

Pour les tests on peut monopoliser quelques machines de l'ENS lundi et mardi.

**Comment by yhamoudi** [comment]
ok. la compatibilité n'est pas un gros problème (je pense qu'on a assez de tests pour sat, et on traitera tseitin et color à part), si j'ai le temps je re-générerai les bdd pour que les profs puisse toutes les manipuler. je commence à écrire une procédure d'utilisation des scripts ruby (qu'on modifiera suivant les modifs en cours)

**Comment by yhamoudi** [comment]
voilà la commande qui ne passe pas (en fait ça ne génère aucun bug, mais au moment de faire un to_gnuplot il y a absence de données) : 

```
l = select_data(100,nil,nil,["wl","dpll"],nil,0) { |p,r| ["#{p.algo}+#{p.heuristic}",p.l,r.result.timers["Time (s)"]/r.count] }
```

**Comment by yhamoudi** [comment]
je viens aux nouvelles :)
tu as une idée pour la commande précédente ? j'aimerai bien mettre en forme quelques courbes ce soir mais je ne peux pas choisir d'heuristiques spécifiques (c'est bizarre parce que si je met 10..100 par exemple en argument pour n, ça marche bien). Fais attention avec le code contenu actuellement dans base.rb, il y a 2 petites modifs qui font que c'est du tseitin maintenant

est-ce que tu penses qu'on pourra lancer des tests pour cette nuit (mon ordi est dispo) ?

Je pense finir l'analyse des résultats sur problème classique / tseitin ce soir. Il restera à faire colorie (peut-être que je ferais du calibrage tout à l'heure).

**Comment by ilsordo** [comment]
Je peux pas push mais dans base.rb dans le code de select data il faut
remplacer :
      if (algos == nil or algos === p.algo) and (h==nil or h===p.heuristic)
par
      if (algos == nil or algos.contains? p.algo) and (h==nil or
h.contains? p.heuristic)

Je suis en train de finir de bricoler mon truc mais j'ai réussi a me
connecter en ssh aux machines de l'ens donc je le lancerais là bas.

2014-04-07 22:37 GMT+02:00 yhamoudi notifications@github.com:

**Comment by yhamoudi** [comment]
c'est bon, ça marche ! par contre j'ai du modifier contains par include

**Comment by yhamoudi** [comment]
tu peux n'intégrer que les heuristiques ["dlcs","jewa","dlis"] dans tes tests.

Pour tseitin, j'aurai les résultats d'ici demain. Tu peux vois ce que j'ai pris dans le wiki, en sachant qu'à partir de 10000, quelque soit l'heuristique, DPLL timeout, donc j'ai dégagé dpll à partir de 10000 pour gagner du temps.

**Comment by yhamoudi** [comment]
j'ai commencé à déplacer tout ce qu'il faut dans le dossier performances. J'ai distingué deux versions du scripts (et des bdd) : v1 et v2. J'ai fait le déplacement pour la v1, je te laisse la v2 (avec création à la racine de run_tests_v2.rb). Tu pourras ensuite supprimer les dossiers stats_databases et stats_script (j'ai récupéré les bdd)

**Comment by yhamoudi** [comment]
dans un nouveau commit : j'ai ajouté tseitin.rb (aux côtés de color.rb). J'ai l'impression qu'il ne marche pas (il n'affiche pas les problèmes qu'il est en train de traiter). Tu peux jeter un coup d'oeil stp ?

**Comment by ilsordo** [comment]
En fait dans boucle il ne faut pas utiliser les variables définies au
dessus (il faut les ajouter en argument).
Je finis de corriger et je push

2014-04-08 15:25 GMT+02:00 yhamoudi notifications@github.com:

**Comment by yhamoudi** [comment]
merci, je file en logique

**Comment by ilsordo** [comment]
J'ai mis un exemple d'utilisation du nouveau select_data dans color.rb. Il
a une syntaxe un peu plus libre et concise. On peut mettre des contraintes
de la forme:
- :n => 4
- :algo => ["dlis","jewa"]
- :vertices => (1..12)

**Comment by yhamoudi** [comment]
readme de la v1 fini

**Comment by yhamoudi** [comment]
j'aurai pas le temps de finir la bdd de tseitin, je fait mes courbes sur ma vieille base (les courbes seront tout aussi bien, le prof ne pourra juste pas lire la bdd correspondante)

**Comment by ilsordo** [comment]
Ok, je suis en train de traiter les données que tu m'as envoyées.

2014-04-08 22:25 GMT+02:00 yhamoudi notifications@github.com:
