### ISSUE TITLE
dpll : unit prop

### ISSUE THREAD

**Issue by ilsordo** [ilsordo/SAT-SMT-Solver#16]
J'ai réfléchi un peu aux améliorations que l'on voulait apporter à la propagation de contraintes dans dpll. Je résume pour vérifier qu'on avait bien la même idée : 
Après un pari il suffit de regarder dans les clauses "touchées" par ce pari pour chercher les singletons et variables de polarité simple.

Voilà ce que j'ai conclu : 
- Pour la polarité simple il faudrait établir l'ensemble des variables des clauses visitées (avec leur polarité?) puis vérifier pour chacune de ces variables si il y a sa négation ailleurs ( ça c'est rapide ). Je pense que la version actuelle est plus efficace sur cet aspect ( a priori on est en O(nb variables) si on vérifie que les clauseset sont vides en O(1).
- Pour les singletons l'implémentation la plus raisonnable que j'ai trouvée est de garder un clauseset de singletons dans formule_dpll , il devra être initialisé au prétraitement par la méthode actuelle puis mis à jour dans set_val / reset_val pour que _tous_ les singletons soient dedans. Cela revient à regarder clause#size quand on enlève des littéraux dans set_val et quand on restaure une clause vide dans reset_val, le problème c'est que la fonction cardinal de Set n'est pas en temps constant (même pas récursive primitive ...) il faut donc ajouter un compteur aux varset pour tricher.

Si tu es ok avec ces modifications je peux m'y mettre dès que j'ai fini de convertir WL

**Comment by yhamoudi** [comment]
- Pour la polarité simple, ça ne semble pas nécessaire de modifier la fonction actuelle
- Pour les singletons : je ne sais pas si j'ai bien compris ce que tu veux dire. Pourquoi stocker les clauses singletons à part ? Si effectivement on n'a pas la taille d'un set en temps constant (d'ailleurs t'as trouvé où cette info ?) on peut ajouter un champ taille dans les clauses que l'on met à jour (c'est ce que tu dis ?), et lorsqu'on assigne un littéral l à vrai, là où l apparaît on regarde si on forme un singleton.

Fondamentalement, ces histoires de propagation ont une mauvaise complexité et c'est WL la propagation des WL qui est utilisée en pratique (d'ailleurs, c'est rappelé dans un doc du prof).

Sinon, j'ai complété le wiki cette aprèm. Je pense y voir un peu plus clair (aussi bien sur WL que DPLL) et je pense qu'il y a suffisamment de similarités entre tous les algos (WL/DPLL +/- clause learning) pour qu'on puisse poursuivre ton unification des algos avec très peu de fonctions qui diffèrent. J'ai mis dans le wiki les infos qu'il faut qu'on maintienne (clause ayant provoqué l'assignation de chaque littéral, niveau de décision...), ainsi que les fonctions/algos à implémenter.

**Comment by ilsordo** [comment]
Les singletons a part c'est pour ne pas avoir a changer le type de retour
de set_val (c'est comme ça qu'on récupérerait les clauses touchées) et
avoir find_singleton en O(nb de clauses intéressantes). Pour la taille des
clauses je pensais effectivement le faire avec un champ supplémentaire.
J'essaie de l'implémenter demain et on pourra passer au learning (après un
petit détour par l'anglais et le dm d'algo :( )

**Comment by ilsordo** [comment]
Voilà j'ai commit mon implémentation, les gains ont l'air faibles ( je gagne ~0.1s sur un temps d'execution de 4s avec dlis ).

**Comment by yhamoudi** [comment]
tu es sur que tu as commit ? je ne trouve pas les améliorations sur les singletons

**Comment by ilsordo** [comment]
Oups, c'est fait maintenant, je pense que j'aurais bientot fini WL.
