### ISSUE TITLE
algo_wl

### ISSUE THREAD

**Issue by ilsordo** [ilsordo/SAT-SMT-Solver#17]
J'ai traduit algo wl mais il y a un problème quelque part. Pour débugguer il faut faire : 
   make debug
   OCAMLRUNPARAM="b" ./resol -d 4 -algo wl tests/cnf/ex1.cnf

pour avoir la pile des appels. On voit que c'est un pari qui est défait 2 fois et je ne vois pas pourquoi. Il y a un point que j'ai adapté de manière douteuse dans algo_wl (il y a un commentaire). Je réessaierais ce soir.

**Comment by yhamoudi** [comment]
je regarde

**Comment by yhamoudi** [comment]
j'ai repéré ton commentaire dans algo_wl (ligne 30). Tu mets : 
 `raise (Conflit ((b,v)::acc))`
Tu vas clairement avoir, dans certain cas, (b,v) qui apparaît 2 fois dans l'accumulateur. Ex : tu assignes (b,v), ça rentre dans la propagation avec acc=[(b,v)] et ça trouve direct un conflit (Wl_conflit). Conséquence : ça raise [(b,l),(b,l)] puis tu imagines la suite (tentative de défaire un pari 2 fois).
Si tu changes ta lignes en : 
 `raise (Conflit (acc))`
ça marche bien sur les 5 exemples du profs (argument de compacité : ça marche sur toutes les cnf du monde :)

**Comment by ilsordo** [comment]
Vive le théorème de compacité! J'ai lu tes pensées et je pense que l'on peut garder la structure actuelle ( appels récursifs ) en ajoutant un resultat Backtrack of int qui traverse juste les étapes qui doivent juste être annulées et en ajoutant de quoi construire les clauses apprises au moment des conflits. La manipulation de l'etat ne me satisfait pas complètement (il y a encore de la répétition), je pense qu'on pourrait en faire une classe qui serait héritée dans dpll et wl, comme ça on peut partager le fait que l'on stocke une pile de tranche, une formule et plus tard un ensemble de clauses apprises par exemple.
