### ISSUE TITLE
Clause learning et singleton

### ISSUE THREAD

**Issue by yhamoudi** [ilsordo/SAT-SMT-Solver#18]
Help ! J'étais convaincu qu'on avait résolut le pb des clauses singletons à apprendre, mais maintenant je doute.

Déjà une remarque : le littéral d'une clause singleton a forcément été assigné au niveau courant (je peux le prouver si tu n'es pas d'accord). Ce matin, on avait dit que ce n'était pas forcément le cas et qu'il fallait différencier le fait que le littéral de la clause singleton est était : jamais assigné / assigné à un niveau > 0, c'est faux.

Il y a donc 2 possibilités pour le backtrack : 
- revenir systématiquement au niveau 0. On est sur que ça marche mais on perd tous les paris effectués en cours de route
- revenir juste un niveau avant, assigner le littéral singleton (en lui attribuant le niveau 0) puis ... que faire ? Si on poursuit la propagation comme si de rien était, il y aura des littéraux assignés par propagation habituelle, et d'autre assignée par propagation nécessaire (ie qui seraient assignés si on revenait au niveau 0).

Fondamentalement, je pense que les 2 cas ci-dessus pourraient marcher. Il semble préférable d'implémenter le 2ème mais je n'arrive pas à me convaincre que tout se passerait bien. Tout de suite, un exemple : 

```
Clauses : 

4
5 6 -4
1 2 -4
-1 2 -4
1 -2 -4
-1 -2 -4

clause 1 : assigner 4

pari 5
  clause 2 : assigner 6

pari 1
  clause 4 : assigner 2
  clause 6 : conflit sur 2
              -1 -2 -4 + -1 2 -4 = -1 -4
  apprendre -1

assigner -1 (au "niveau 0" )
au niveau de pari 5, poursuivre : 
  clause 3 : assigner 2
  clause 5 : conflit sur -2
              1 2 -4 + 1 -2 -4 = 1 -4
  apprendre 1 -4 ???
    >> c'est une clause vide donc ça mq UNSAT ?
    >> on ajoute cette clause et on trouve le conflit sur clause vide au niveau 0 ?
```

**Comment by ilsordo** [comment]
Quand tu dis "apprendre -1 en fait c'est -1 -4 et 4 est toujours à vrai non?

**Comment by yhamoudi** [comment]
ah oui, j'ai fait une erreur. Du coup mon histoire de clause vide ne marche pas (ici).

Tu penses que si on ne backtrack pas systématiquement au niveau 0 ça se passe bien ?  On assigne juste le littéral singleton puis on poursuit la propagation normalement sur la tranche du dessous ? Et UNSAT aurait lieu lrosqu'on trouve un conflit au niveau 0 ?

**Comment by ilsordo** [comment]
Je pense que ça devrait marcher, sinon je vois 2 problèmes qui peuvent apparaitre : 
- Peut être ce que tu appelles un conflit au niveau 0: on a ajouté x et -x -> il faut dire tout de suite que c'est UNSAT (On le verra car le niveau de pari de x est 0)
- Est ce que dans la construction de l'UIP on va avoir un problème du à l'assignation au niveau 0 de x?

Pas vraiment en rapport mais ça m'embête pour le graphe/preuve de l'UIP: 
On est d'accord que l'algo de construction de l'UIP ne trouve pas nécessairement l'UIP le plus proche du conflit?

**Comment by yhamoudi** [comment]
A mon avis il y a 2 types de conflits au niveau 0 : 
- les clauses vides. 
- les doubles assignations (x et -x). Je ne pense pas que c'est censé arriver : au moment où on assigne x au niveau 0 (à supposer que x est assigné avant -x) , on peut créer des clauses vides (là où -x figure) et ça doit entraîner ici la détection de conflits (sans qu'on ai besoin de parier -x plus tard). Une fois qu'on a quitté le niveau 0 (en ayant réussi à assigner x par exemple), on est plus jamais censé rencontrer -x.

Pour la construction du graphe de conflit : il faut remonter toute la tranche courant (jusqu'au pari), alors que conflict_analysis s'arrête dès que la clause en cours d'apprentissage contient un seul littéral assigné au niveau courant. Donc ton graphe contient toutes les UIP (et je crois qu'il faut distinguer sur le graphe l'UIP utilisé).

Pour l'UIP et le niveau 0, je réfléchis encore.

**Comment by yhamoudi** [comment]
ah oui et pour l'état tu as réussi à l'implémenter ?

**Comment by ilsordo** [comment]
J'ai essayé plein de trucs, tu as commit tout ce que tu as à faire (modulo les détails) pour l'algo?

La seule chose qui parait raisonnable est de revenir vers le premier truc qu'on avait fait avec la formule à coté de l'état et une fonction get_formule : Base.formule -> formule qui fait un cast. Du coup on peut exposer la partie commune de l'état et ne passer que ce qu'il faut aux fonctions (genre la dernière tranche ou la pile ou tout l'état s'il le faut) et récupérer un ou des éléments à modifier.

**Comment by yhamoudi** [comment]
je viens de commit (pas de grosses modifs depuis la fin d'aprèm).

**Comment by yhamoudi** [comment]
Bon, je reviens à la charge sur les clauses singletons (désolé). Un exemple où j'utilise l'algo qu'on avait dit (c'est bien ça ?) : 

```
Clause 1 : 3 -4
Clause 2 : 5 6 7
Clause 3 : -5 -6 -7
Clause 4 : 1 2
Clause 5 : 1 -2
Clause 6 : -1 4 -3
Clause 7 : -1 -4
Clause 8 : -1 8
Clause 9 : -1 -8

Niveau 0 

Niveau 1
  pari 3

Niveau 2
  pari 5

Niveau 3
  pari -1
  Clause 4 : assigner 2
  Clause 5 : conflit sur -2
    1 2 + 1 -2 = 1
  apprendre 1 (ne pas enregistrer la clause, car singleton)

Niveau 0
  assigner 1

Niveau 2 (soit un niveau avant le moment où le conflit à provoqué l'apparition d'un singleton)
  poursuivre la propagation
  Clause 7 : assigner -4
  Clause 6 : conflit 4
    apprendre -1 4 -3 (seul 4 est de niveau 2) (puis backtrack au niveau 1)

Niveau 1
 poursuivre propagation
 Clause 6 (aussi clause apprise) : assigner 4
 Clause 7 : conflit sur -4
   apprendre -1 -4 (backtrack au niveau 0)

Niveau 0
  poursuivre propagation
  Clause 7 (aussi clause apprise) : assigner -4
  Clause 6 : clause vide >> BOUM !

ou alors (autre comportement possible à partir du dernier niveau 2 ci-dessus) :
Niveau 2 (soit un niveau avant le moment où le conflit à provoqué l'apparition d'un singleton)
 poursuivre la propagation
 Clause 8 : assigner 8
 Clause 9 : conflit sur -8
    apprendre -1 -8 (puis backtrack au niveau 0, car -1 est de niveau 0)

Niveau 0    
 poursuivre propagation
 Clause 9 (aussi clause apprise) : assigner -8
 Clause 8 : clause vide >> BOUM !


```

tu penses qu'en implémentant cette procédure ça marche ?

**edit** : c'est le passage _"soit un niveau avant le moment où le conflit à provoqué l'apparition d'un singleton"_ qui est décisif : on assigne au niveau 0 mais on n'y reste pas pour propager

**Comment by yhamoudi** [comment]
j'avais une erreur dans l'exemple, c'est corrigé. La question c'est : est-ce que la procédure te semble correcte (moi je trouve bizarre de faire des sauts au niveau 0 sans y rester pour propager, mais ça semble marcher ...)

**Comment by ilsordo** [comment]
Quand tu fais "assigner 4" au niveau 1 c'est bien une propagation? Si c'est le cas je pense que c'est bon, après je pense qu'une fois que tout fonctionnera il pourrait être intéressant d'essayer de remonter complètement si on apprend un singleton pour comparer les performances.

**Comment by yhamoudi** [comment]
oui, c'est bien une propagation. ok, on essaiera ça

**Comment by yhamoudi** [comment]
voilà, c'est implémenter. 
La principale modif : maintenant conflict_analysis renvoie un triplet (l,lvl,sgt) où l est le littéral à assigner en priorité, lvl le niveau de backtrack, et sgt est un booléen vrai ssi la clause apprise était un singleton (dans ce cas, on assigne l au niveau 0, puis on continue_bet au niveau lvl)
je debug dès que l'état est opérationnel :)

**Comment by yhamoudi** [comment]
si tu as le temps aujourd'hui tu peux implémenter la structure générale de l'état stp (je déplacerai les méthodes et j'adapterai le reste du code), je suis chaud pour debugger ce soir :)

**Comment by ilsordo** [comment]
Ok je m'y met, avec un peu de chance ça marchera du premier coup :)

**Comment by ilsordo** [comment]
Presque fini, je lutte un peu avec les arguments optionnels.

**Comment by ilsordo** [comment]
Je rectifie, c'est l'horreur ! La fusion ne s'est pas super bien passée et il faut que je traque les trucs dont le nom est différent entre tes fichiers et les miens ...

Et tu avais réutilisé != à un endroit.

**Comment by yhamoudi** [comment]
tu as travaillé sur quelle version des fichiers ? (parce que le seul commit que j'ai fait aujourd'hui contenait peu de différences par rapport à hier soir)

**Comment by ilsordo** [comment]
Je crois que j'avais ceux d'hier soir, je suis pas sûr, tu as changé quand Clause_vide en Empty_clause?

**Comment by yhamoudi** [comment]
j'ai renommé/unifié les messages d'erreurs hier soir

**Comment by ilsordo** [comment]
Ok donc j'avais n'importe quoi, Du coup de vais finir le merge quand même sinon je dois tout réécrire. Je commit quand ça compile ( ou quand je ne comprendrais plus les messages d'erreur )

**Comment by ilsordo** [comment]
C'est bon, par contre (comme on peut s'y attendre) ça crashe. Je te laisse faire une passe de debug, je vais bosser sur les représentations/interactions.

**Comment by yhamoudi** [comment]
super, merci !

**Comment by yhamoudi** [comment]
1ère étape finie : ça marche sans l'apprentissage de clause !

**Comment by yhamoudi** [comment]
un petit avancement sur le debuggage : 
- quelques petits bugs sournois (une tranche non dépilée...)
- 2 bugs plus profonds : 
  - c'est plus difficile qu'il n'y parait d'implémenter correctement algo (dans algo.ml) pour qu'il soit commun à avec/sans clause learning. Le plus gros problème c'est le backtrack non chronologique (du clause learning). Sans le clause learning, l'empilement des appels à process et aux est bien cohérent (et chronologique !). Avec clause learning, on s'amuse à dépiler des tranches sans retourner de pièces et ça provoque un retour trop rapide au premier appel de aux. La conséquence, c'est d'obtenir en sortie Deep_backrack (ce qui signifierait une demande de backtrack sur le niveau 0, donc UNSAT) alors qu'il y a encore de quoi backtracker ! Pour résoudre ça, je travaille pour l'instant sur un algo modifé qui ne fait que du clause learning, et je pense pouvoir le fusionner avec l'algo du non clause learning en abandonnant le type Deep_backtrack (et en récupérant l'erreur Init_empty si UNSAT).
  - ce qui m'embête le plus actuellement : gérer les clauses singletons (!). Un problème que l'on n'avait pas envisagé s'est manifesté sur ex1.cnf. Je résume le comportement fautif : 
    - on a une clause singleton sur l
    - on assigne l au niveau 0 (sans défaire les niveaux intermédiaires)
    - dans les clauses où non l apparait, il faut cacher non l
      - si clause pas cachée << ok, on la cache
      - __si clause déjà cachée (via une assignation d'un niveau supérieur) << il faut la trouver ! __
    - dans les clauses où l apparait, il faut
      - cacher la clause << ok
      - **cacher la clause pour les lit apparaissant dedans, _sauf_ pour l << il faut trouver le seul l0 qui connait encore l pour y cacher la clause !**

Les 2 points en gras sont embêtants. Ils peuvent se résoudre à coup de fold_all/iter_all mais la complexité n'est pas géniale (quel est l'intérêt de cacher des clauses/littéraux si c'est pour rechercher ensuite dedans) et c'est délicat à manier. Du coup 2 possibilités : j'essaye de gérer ces cas, ou on backtrack systématiquement au niveau 0 dans le cas d'un singleton ?

(j'ai enfin trouvé un document évoquant l'existence de clauses singletons à apprendre. C'est une thèse, et l'auteur indique de revenir systématiquement au niveau 0 dans le cas de singletons. Ceci dit, rien n'est détaillé et le document est moyennement convainquant)

**Comment by ilsordo** [comment]
Autant éviter de rendre l'algo encore plus compliqué, je pense que le retour à 0 est plus simple, de toute manière on peut se convaincre qu'une assignation inconditionnelle est très importante pour accélérer l'algo (On dirait pas mais dans le pire cas (du coup le meilleur pour nous) assigner une variable c'est réduire de moitié l'espace de recherche restant).

**Comment by yhamoudi** [comment]
C'est bon, le clause learning est opérationnel sur DPLL (il est activé par défaut, pour l'enlever : mettre false dans ?(cl=true(***)) dans algo.ml)

J'attaque WL

**Comment by yhamoudi** [comment]
et voilà : WL est opérationnel avec/sans clause learning !!!

Pour activer le clause learning : ajouter l'option -cl

Un truc à faire : il faut unifier algo_wl.ml et algo_dpll.ml. Hormis les fonctions constraint_propagation, tout est identique (à 4 lignes près qu'on peut transformer en arguments optionnels). 

Sinon, au niveau des performances : j'ai pas poussé les tests mais sur un certain nombres de fichiers, le clause learning ralenti l'exécution ! Je vais regarder ça plus en détail pour savoir si c'est lié à un problème d'implémentation (par ex : clauses apprises non enregistrées), où si c'est normal.

**Comment by yhamoudi** [comment]
j'ai tout remonté sur la branche master, on peut travailler directement dessus maintenant (et détruire clearning en toute sécurité ? je te laisse faire)

**Comment by yhamoudi** [comment]
Pour revenir sur les performances : il y avait effectivement un problème dans dpll. Les clauses apprises restaient cachées. Ça améliore les temps d'exécution mais la différence entre avec/sans clause learning n'est pas flagrante (aussi bien avec dpll que wl). Je poursuit les investigations...

(j'ai ajouté une heuristique next_next qui pari en priorité true sur le plus grand littéral dispo. C'est plus simple pour dérouler les algos à la main d'avoir une heuristique déterministe et pas trop complexe dans ses choix...)

**edit** : bon je pense que tout est ok maintenant. Il faudra lancer des tests plus poussés pour comparer les perfs (il y a quand même de grosses améliorations sur certains fichiers grâce au clause learning). J'ai renommé certains timers

**Comment by yhamoudi** [comment]
Un exemple de performance plutôt bof (ça arrive surtout sur des formules unsat). J'ai généré un (200,3,954) insatisfiable. Les temps d'exécution WL+DLCS (d'abord avec clause learning, puis sans) : 

![perf](https://cloud.githubusercontent.com/assets/6659728/2751449/9f3fb774-c8ce-11e3-8d40-6dc5cb801a88.png)

On remarque que le clause learning est meilleur dans la résolution en elle-même : près de 2 fois moins de conflits/paris grâce au clause learning ! En contrepartie, le temps de décision explose (et pourtant c'est dlcs) : 10 fois + long avec clause learning. L'explication me semble assez simple : un conflit = une clause ajoutée. Donc 95188 conflits (dans le cas clause learning), c'est 95188 clauses ajoutées !!! Evidemment le temps de décision devient énorme (on reparcourt à chaque fois toutes les occurrences de toutes les variables), et la propagation aussi.

Il y a 2 choses à faire à mon avis : 
- déjà gagner un peu de temps sur le comptage du nombre d'occurrences. Je vais voir pour faire comme ce que tu as implémenté pour les clauses, afin d'avoir la taille en temps constant.
- il faut être plus malin sur les clauses ajoutées. Je répertorie des heuristiques dans le wiki. Ce qui est possible : vieillissement des clauses (ça me semble indispensable), minimisation de la taille des clauses ajoutées (j'ai pas encore tout compris à ce sujet)... A ce sujet, où il serait malin d'enregistrer les stats nécessaires à ces heuristiques (dans les stats actuels, dans la formule, ailleurs ?)

**Comment by ilsordo** [comment]
Ok, je suis un peu en retard mais je rattrape demain.

Pour le nombre d'occurences si c'est dans un clauseset tu devrais pouvoir
(quasiment) recopier les fonctions de varset.

Effectivement sans le vieillissement l'apprentissage peut vraiment tourner
au n'importe quoi. Pour les infos il faudrait faire remonter l'analyse de
conflit dans algo donc il semble logique de les mettre dans l'etat, il
pourrait aussi être intéressant de regarder combien de clauses singletons
apparaisent dans la résolution.

2014-04-20 23:12 GMT+02:00 yhamoudi notifications@github.com:

**Comment by ilsordo** [comment]
Par contre il y a un point cool : on est exactement dans la bonne répartition du temps entre propagation/paris.

**Comment by yhamoudi** [comment]
J'ai plein d'autres temps !

DPLL sur le même test : 
![dpll_avant](https://cloud.githubusercontent.com/assets/6659728/2751564/124aff76-c8d9-11e3-9c34-2f8bdce5b855.png)

WL avec taille de clauseset en O(1) : 
![wl_apres](https://cloud.githubusercontent.com/assets/6659728/2751571/3df7e314-c8d9-11e3-8e6f-388755d668c3.png)

WL avec taille clauseset en O(1) et suppression les tests de type "ClauseSet.mem " effectués avant d'ajouter une clause : 
![wl_apres_apres](https://cloud.githubusercontent.com/assets/6659728/2751575/5ce8806c-c8d9-11e3-9c01-ec7845304567.png)

On peut aussi supprimer les tests "mem" dans varset, mais sur l'exemple d'ici ça n'impact pas le temps (c'est normal, les varset manipulés sont petits). Ceci dit, je ne sais pas s'il est judicieux d'enlever ces tests pour les varset (c'est plus "sécurisé" de les garder, mais si on manipule des clauses longues ça peut faire gagner du temps).

**Comment by ilsordo** [comment]
Si on est sûr que c'est vérifié tout le temps on peut mettre un assert sur le cas qui n'arrive jamais, comme ça on peut tester et enlever les assert le jour où il faut aller vite (je crois qu'un flag du compilateur caml le fait mais par contre c'est tous les assert qui disparaissent !)

**Comment by yhamoudi** [comment]
j'avais pas vu tes posts :)

C'est tellement bien programmé que les fonctions de tests dans hide/show/... sont inutiles !

**Comment by ilsordo** [comment]
Parfait alors. En parlant de ça il faudra essayer de mettre des hashmap pour les clauses un jour.

**Comment by yhamoudi** [comment]
question : à quel niveau unifier les fonctions communes à algo_dpll et algo_wl ? Dans algo_base (dans ce cas-là, comment récupérer les fonctions constraint_propagation de wl et dpll (qui sont les seules fonctions qui diffèrent vraiment entre wl et dpll) ?) ?

**Comment by ilsordo** [comment]
Je m'en occupe et je push

**Comment by ilsordo** [comment]
J'ai eu une révélation, tout va être plus simple à partir de maintenant (Et c'est pas fini :) ), il me faut encore un peu de temps pour réordonner les algos mais je crois avori compris le truc avec private qu'on avait vu à la fin du dernier cours.

**Comment by ilsordo** [comment]
J'ai push, il y a une erreur sur ex2.cnf je vais essayer de voir d'où ça vient. (branche unif)

**Comment by yhamoudi** [comment]
j'ai aussi l'erreur, sans avoir récupéré tes modifs :( j'ai du faire une erreur dans une modif mineure récente, je regarde

**Comment by ilsordo** [comment]
Ok

**Comment by yhamoudi** [comment]
c'est bon : dans clause.ml, parmi les lignes commentées (afin d'éviter les VarSet.mem), il y en a une qu'il faut garder.

**Comment by ilsordo** [comment]
Tu as commit?

**Comment by yhamoudi** [comment]
voilà, c'est bon

**Comment by yhamoudi** [comment]
j'ai regardé ton code, c'est parfait. Tu peux fusionner les branches je pense.

**Comment by ilsordo** [comment]
Tadaa! J'ai cafouillé sur les merge, je croyais que tu avais commit sur master, donc l'historique risque d'être joli à cet endroit.

**Comment by yhamoudi** [comment]
J'ai ajouté plein de timers. Les résultats sur le fichier strange.cnf (dans dossiers tests) : 

```
[debug] Using algorithm wl and heuristic dlcs with clause learning
s UNSATISFIABLE

[debug] Stats :
[stats] Conflits = 95188
[stats] Paris = 108213

[timer] Total execution (s) : 443.72400
[timer] Clause learning (s) : 12.45600
[timer] Decisions (s) : 5.34000
[timer] Propagation (s) : 423.16800
[timer] Bactrack (s) : 1.36000

[debug] Using algorithm wl and heuristic dlcs 
s UNSATISFIABLE

[debug] Stats :
[stats] Conflits = 196381
[stats] Paris = 196380

[timer] Total execution (s) : 43.80000
[timer] Decisions (s) : 6.83600
[timer] Propagation (s) : 33.70000
[timer] Bactrack (s) : 2.04800

[debug] Using algorithm dpll and heuristic jewa with clause learning
s UNSATISFIABLE

[debug] Stats :
[stats] Conflits = 14232
[stats] Paris = 17063

[timer] Total execution (s) : 213.94400
[timer] Clause learning (s) : 1.74000
[timer] Decisions (s) : 41.43600
[timer] Propagation (s) : 58.26400
[timer] Bactrack (s) : 85.73600

[debug] Using algorithm dpll and heuristic jewa 
s UNSATISFIABLE

[debug] Stats :
[stats] Conflits = 52473
[stats] Paris = 52472

[timer] Total execution (s) : 72.46000
[timer] Decisions (s) : 31.17600
[timer] Propagation (s) : 20.59600
[timer] Bactrack (s) : 18.88800
```

**Comment by ilsordo** [comment]
C'est quand même étrange que wl prenne aussi cher sur la propagation, il est censé être plus performant sur de grosses clauses non?

**Comment by yhamoudi** [comment]
C'est pour ça que le fichier s'appelle strange.cnf.

Je sais pas si c'est bizarre. A la fin de l'exécution (wl + clause learning), on a près de 100 000 clauses. Donc longues ou pas ça fait cher la propagation. D'un autre côté dpll avec clause learning propage/backtrack plus rapidement, mais avec seulement 15 000 clauses (ce qui fait quand même pas mal pour dpll).

Je vais vérifier le code de wl pour voir s'il n'y a pas de bêtises dedans.

**Comment by yhamoudi** [comment]
j'annonce une nouvelle heuristique dans le monde du sat solving. commit dans la soirée !

**Comment by yhamoudi** [comment]
et voilà, c'est push :)
Pour l'instant c'est artisanal : il faut commenter/décommenter la ligne 309 dans algo.ml pour activer ou non l'heuristique. A noter (cf description après) que c'est une heuristique WL exclusivement.

**Principe de fonctionnement :** dans WL, on restreint la propagation aux littéraux surveillés. Ça permet de propager rapidement mais en contrepartie il y a plein de clauses vraies sans qu'on le sache. Pour remédier à cela facilement/rapidement (ie sans maintenir les occurences pos/neg qui nous ramènent  in fine à du dpll), on ne le fait que périodiquement ! Par exemple, tout les 1000 conflits, on prend le temps de parcourir toutes les clauses et de déplacer là où s'est possible les jumelles sur des littéraux vraies. Comme c'est une heuristique de champion, ce déplacement des jumelles est malin : il cherche en priorité à surveiller les littéraux dont le niveau d'assignation est le plus faible (intuitivement : c'est les littéraux les plus stables).

Je ne sais pas si l'amélioration des performances (pas si _exceptionnelle_ en fait) vient du déplacement périodique des jumelles ou du fait de surveiller des littéraux avec un faible niveau d'assignation en priorité. Je pense que la combinaison de ces 2 trucs donne lieu à un "restart du pauvre" : on ne prend pas la peine de faire sauter toutes les tranches d'assignations, mais on se rapproche quand même pas mal du niveau 0.

Le facteur clé de l'heuristique c'est la période d'attente entre deux déplacements massifs de jumelles. Actuellement (ligne 306) c'est 1000 conflits. J'ai l'impression (sur les qqs tests effectués) qu'il ne faut pas hésiter à mettre ce facteur très bas : ça semble améliorer les perfs, et le timer sur cette zone est faible. 

J'ai vu passer des assert false pour une période de 500 conflits, sur strange.cnf (dans tests). ça vient de dlcs (dans heuristic.ml), ligne 70 --> seul explication possible à mes yeux, la taille des clauseset (ici clauses surveillées par chaque littéral) devient négative à un moment (add/remove fictifs). C'est peut-être due à mon heuristique qui effectue mal une permutation de jumelles...

Et maintenant les résultats tant attendus. Sur les tests effectués (moins de 10 tests ! mais par compacité ...), j'ai l'impression que l'heuristique aide bien le clause learning, mais n'améliore pas significativement le non clause learning. A mon avis, c'est lié au fait que le clause learning génère énormément de clauses.

Résultats pour strange.cnf (shaking : tps passé par l'heuristique, comparer aussi le nb de conflits pour voir la pertinence de l'heur dans le cas clause learning) : 

**Avec heuristique** : 
![heurcl](https://cloud.githubusercontent.com/assets/6659728/2770916/72891062-ca64-11e3-9ac9-8e36666f7361.png)

**Sans heuristique** : 
![wl_apres_apres](https://cloud.githubusercontent.com/assets/6659728/2770905/4ca5845c-ca64-11e3-8977-135cbaf2e92c.png)

**Comment by ilsordo** [comment]
Pas mal! Moi je peine avec mes graphes... par contre ce serait peut être plus prudent de mettre ça sur une branche séparée non? Comme ça tu peux l'essayer avec checkout puis make et en faisant des commits réguliers il sera facile de l'intégrer correctement plus tard.

**Comment by yhamoudi** [comment]
Oui, je ferais le déplacement demain. On regardera cette histoire de graphe demain matin (tu n'arrives pas à choisir les couleurs ?)

**Comment by ilsordo** [comment]
Ahah, si mais c'est le orange qui ne veut pas s'afficher dans le cas où l'uip est le pari ( premier conflit sur ex2.cnf). J'essaie encore un peu pour qu'on puisse réfléchir sur où améliorer les perfs du clause learning demain.

**Comment by ilsordo** [comment]
J'ai identifié le problème, je m'en occupe demain, pour le moment on dessine tout le graphe de la tranche et tout devrait marcher si l'uip est facile à trouver ( pas d'autres puits que le conflit )

**Comment by yhamoudi** [comment]
J'ai résolu le pb des mem. Ça ne touchait que les singletons et c'était localisé dans reset_val.

**L'explication** (à première vu, les faits qui suivent pourraient aussi se produire sur les autres clauseset que l'on utilise, d'où la nécessité de rétablir partout les vérifications mem. En pratique, ce n'est le cas sur aucun des tests que j'ai effectués, donc je n'ai mis des mem que pour les singletons...) :

Clause 54 : 13 16 18

on pari -13 et -16
on ajoute la clause 54 aux singletons (seul 18 est non assigné)
via une autre clause, on assigne -18 et on trouve un conflit avant d'avoir pu rencontrer ce singleton 54
on commence le backtrack, et on dé-assigne 18 (avant 13 et 16). Au moment de faire le reset sur 18, on se rend compte que clause 54 est singleton et on veut l'ajouter une deuxième fois !!!

++ d'autres phénomènes du même genre dans reset

**Comment by yhamoudi** [comment]
tu pourras ajouter l'option clause learning à ton script ce soir ? je lancerai des tests cette nuit

**Comment by ilsordo** [comment]
Ok je l'ajoute et je mets un exemple dans exemple.rb

**Comment by yhamoudi** [comment]
merci pour le script. Je ferais le renommage pour les nouveaux timers et je m'occupe du readme ce soir.
Juste une question pour accélérer les tests : est-ce qu'il y a moyen de lancer dpll+moms mais pas wl+moms (qui timeout systématiquement) par exemple ?

**Comment by ilsordo** [comment]
Le plus simple si tu as peu de tests est de copier le code de run_tests et remplacer algos.each do |a_| h.each do |h_| ... end end par

couples.each do | a_,h_ | où tu spécifie les couples. par exemple couples = [["dpll","moms"],["wl","dlis"],["dpll","dlis"]], sinon il faut recycler le code qui se rappelle de qui timeout dans script.rb.

**Comment by yhamoudi** [comment]
c'est parfait ça, je prends !

**Comment by yhamoudi** [comment]
Voilà ce que je te propose pour les tests : 

```
  couples = [["dpll","moms"],["wl","dlcs"],["dpll","jewa"],["dpll","dlcs"],["wl","jewa"]]
  n = [100,150,200,250,300]
  l = [3]
  k = (1..20).map {|x| 100*x}
  cl = [true,false]
  sample = 3                   
  timeout = 600 << c'est élevé
```

J'ai exclu les heuristiques les moins bonnes. Le prof demande aussi Rand dans le rendu mais on peut peut-être ne pas le mettre (ça va juste faire du timeout dans tous les sens...) ?

Ça te convient ?

**Comment by ilsordo** [comment]
Parfait, peut être que tu peux restreindre k aux alentours de la zone intéressante, non?

**Comment by yhamoudi** [comment]
c'est déjà bien restreint : en dehors de la zone de transition, les temps sont si faibles que ce n'est pas un pb (cf performances rendu 2)

**Comment by ilsordo** [comment]
C'était à ça que je pensais, mais effectivement ce sera vite passé et ça donnera des jolies courbes

**Comment by yhamoudi** [comment]
J'ai fait un commit avec : 
- une première maj du README
- une maj du TODO avec ce qui nous reste à faire
- la suppression de mon heuristique sur WL

Les tests tournent (beaucoup de timeout, j'ai ré-haussé la limite à 700s mais il va manquer bcp de données).

**Comment by ilsordo** [comment]
Ok, je livre une bataille sans merci au compilateur pour faire marcher l'interaction ce soir et il me restera juste la dérivation.

**Comment by ilsordo** [comment]
Tadaa! Si tu veux afficher le graphe c'est 

```
dot -Tpng example.dot -o graph.png;eog graph.png
```

Au passage je pense qu'on peut fermer cette issue, à part si tu as des ajouts sur cl qui sont encore nécessaires ?
