### ISSUE TITLE
Graphe de conflits

### ISSUE THREAD

**Issue by ilsordo** [ilsordo/SAT-SMT-Solver#19]
J'ai regardé pour mettre une légende et c'est assez compliqué d'avoir un rendu propre donc il vaut mieux le documenter proprement et laisser le graphe faire son travail de graphe.

Du coup je laisse les littéraux pas utiles à l'UIP en pointillé?

**Comment by yhamoudi** [comment]
ok, c'est pas grave. 

Pour les pointillés ça ne me pose pas problème. Essayes sur quelques cnf raisonnables pour voir si le graphe devient excessivement grands...

(analyses de courbes incoming. Ça va révolutionner ta vision de DPLL et WL)

**Comment by ilsordo** [comment]
J'ai enlevé les sommets qui servent à rien mais on peut les rajouter si on préfère dans le futur, essaie sur ex5.cnf on a les 2 cas de figure sur les 2 premiers conflits en faisant juste .resol

**Comment by yhamoudi** [comment]
ah oui, très joli !

Je résume les codes couleurs (sans donner le vrai nom des couleurs :) : 
- rouge : le conflit
- gris : littéraux pas au niveau courant
- bleu : littéraux du niveau courant
- orange : unique littéral du niveau courant dans la clause à apprendre
- vert : pari 
- contour en orange : c'est le littéral parié qui est l'unique litt de niveau max
- dans le bloc clause : les littéraux de la clause à apprendre

Il faudra une option (-interac ou autre) pour activer l'interaction (ne pas la mettre par défaut), et quelque chose pour simplifier l'affichage du graphe (tu me parlais d'un script ce matin ?)

Sinon, j'ai finit les courbes (ça m'a permit de découvrir pas mal de trucs intéressants). Je poursuit la rédaction du Readme...

**Comment by yhamoudi** [comment]
j'ai eu qqs soucis dans les commits. Je viens de faire un merge (avec des modifs dans algo.ml, dont une modification du type t) et à la compilation j'ai des warnings dans interaction. C'est normal ?

**Comment by ilsordo** [comment]
Pour l'option c'est fait :) -i.
Normalement l'UIP devait pas être rempli en orange mais ça rend pas mal, je peux le remettre en bleu si tu veux.

Je commence la résolution et je me rend compte qu'on va avoir 3 3 fois le même parcours. Par contre cette fois je suis pas sûr qu'on puisse (ni qu'il soit très utile de )  les unifier donc tant pis.

**Comment by ilsordo** [comment]
Les warnings viennent d'un morceau pas fini, pas de problème :)

**Comment by yhamoudi** [comment]
je viens de pull (43 minute après...) mais ça ne compile plus

**Comment by ilsordo** [comment]
Zut, je regarde

**Comment by yhamoudi** [comment]
il indique une erreur de parenthèse  mais ça ne semble pas être seulement ça

**Comment by ilsordo** [comment]
Le problème est que j'ai bêtement push interaction.ml qui est en travaux, je le mets dans un état correct et j'envoie.

**Comment by ilsordo** [comment]
Voilà

**Comment by yhamoudi** [comment]
c'est bon, merci

**Comment by yhamoudi** [comment]
Quelques questions  : 
- j'ai intégré des stats dans certaines fonctions présentes dans algo.ml (dont conflict_analysis à l'instant). Fait attention à ne pas appeler ces fonctions pour ne pas fausser les statistiques/timers
- j'ai ajouté les stats "Learnt clauses" et "Learnt singletons" (si tu as une meilleur idée de noms...)
- d'autres stats à ajouter ?
- et juste un rappel (mais je crois que tu as fait attention) : l'interaction ne pré-suppose pas clause learning activé.

**Comment by yhamoudi** [comment]
Révélation : il semble qu'il n'y ait que très rarement des singletons à apprendre !

**Comment by ilsordo** [comment]
Je n'utilise pas les fonction d'algo.ml pour construire les infos. Pour les noms c'est bon, on fera de la poésie plus tard :) . Tu peux tester l'interaction, elle marche avec et sans cl.

**Comment by yhamoudi** [comment]
oui, je n'avais pas constaté de pbs dans l'interaction avec cl. Par contre le debug semble toujours au niveau 1, c'est normal ?

**Comment by ilsordo** [comment]
Euh, je ne crois pas y avoir touché. Je regarde.

**Comment by ilsordo** [comment]
Tout marche chez moi.

**Comment by yhamoudi** [comment]
j'ai rien dit, c'était un truc local

**Comment by yhamoudi** [comment]
et voilà : j'ai fini la rédaction des readme/analyses. Il faudra compléter le readme sur la résolution, et relire le paragraphe 12. J'ai fait des tests un peu partout et tout semble très bien marcher.

Tu t'en sorts avec la construction de la preuve ? je peux t'aider à debugger si tu as besoin d'aide

**Comment by ilsordo** [comment]
J'étais parti sur un algo différent mais c'était pas pratique donc je réécris à la manière de print_graph, j'ai créé des scripts et modifié un peu le comportement de print_graph (et print_resol) pour que quand on fait g example le fichier example.dot soit créé et on a juste à appeler ./print_graph example pour l'afficher. Ca permet de nettoyer les trucs laissés par la compilation latex et d'afficher directement les fichiers générés.

**Comment by ilsordo** [comment]
J'essaie de sortir vite quelque chose qui marche sans couper les preuves et après j'essaierai d'améliorer autant que possible. Il me reste des choses à écrire dans les README?

**Comment by yhamoudi** [comment]
non, c'est tout bon. Juste faire des corrections si tu as modifié la syntaxe dans l'interaction

**Comment by ilsordo** [comment]
Ok cool, j'ai déjà tout l'affichage de prêt, il me reste juste à finir de construire les preuves

**Comment by ilsordo** [comment]
C'est encore crade mais ça devrait passer une fois débuggué

**Comment by ilsordo** [comment]
Aaaargh j'ai écrit des choses qui me font pleurer et ça marche presque ...

**Comment by yhamoudi** [comment]
ah ah, laisse moi ajouter des références

**Comment by ilsordo** [comment]
Il y a un TIE fighter dans le code ! :) (<>)

**Comment by yhamoudi** [comment]
pour faciliter le debuggage surement

**Comment by ilsordo** [comment]
Tout compile! Si j'arrive pas à débugguer envoie ta version du code (qui fonctionne) et j'enverrais mes additions dans la nuit ...

**Comment by yhamoudi** [comment]
si tu commit ta version à priori tout marche en dehors de la résolution (donc on peut envoyer celle-là, en précisant que la résolution n'est pas fonctionnelle) ?

Et pour l'envoi "d'additions dans la nuit", je pense pas que ce soit nécessaire. On corrige demain au pire et on renvoie après. T'as le droit de dormir la nuit :) (surtout que vous avez tp d'asr demain je crois)

**Comment by yhamoudi** [comment]
et question : c'est des fichiers .log que tu génères dans la résolution (c'est ce que j'ai lu dans print_resol) ?

**Comment by ilsordo** [comment]
J'avais presque oublié l'ASR ! Effectivement tout compile chez moi et mais r ... crashe. Les fichiers générés sont .dot pour g et .tex pour r

**Comment by yhamoudi** [comment]
pourquoi l'extension .tex n’apparaît pas dans print_resol alors ?

**Comment by ilsordo** [comment]
C'est pour faire le ménage, mon executable affiche des instructions au moment où tu fais 

```
g example
```

il créée example.dot et avec le script ./print_graph il génère graph.png et l'affiche, pareil pour resol

**Comment by ilsordo** [comment]
Et l'appel à print_graph est 

```
./print_graph example
```

Sans extension

**Comment by yhamoudi** [comment]
lorsque je fais g example je devrais voir un graphe apparaître ?

**Comment by ilsordo** [comment]
Non, il faut aller dans un terminal et faire ./print_graph example

**Comment by ilsordo** [comment]
Si je l'ai pas commit je le fais tout de suite

**Comment by ilsordo** [comment]
Chacun des assert false que j'ai écrit est atteint ...

**Comment by yhamoudi** [comment]
effectivement, il me manquait une partie. Je boucle le readme.

**Comment by yhamoudi** [comment]
Oui, je peux voir les jolies assert failure. Il reste 19 min pour corriger ce grand chelem.
(je prépare une archive à envoyer cas ou...)

**Comment by ilsordo** [comment]
Bonne idée

**Comment by yhamoudi** [comment]
tu as bien fait tous les git add nécessires ?

**Comment by ilsordo** [comment]
Tout ce qu'il me reste c'est des fichiers générés. Tu veux que je modifie interaction pour désactiver r?

**Comment by yhamoudi** [comment]
non, je préciserai dans le mail de ne pas l'utiliser

**Comment by ilsordo** [comment]
Ok :)

**Comment by ilsordo** [comment]
J'ai corrigé 1 bug!

**Comment by yhamoudi** [comment]
j'ai un problème pour faire l'archive : il inclue tous les fichiers cachés (..~) et produit une archive trop lourde. Comment je peux les dégager ?

**Comment by ilsordo** [comment]
rm **/**~ devrait marcher sinon je m'en occupe

**Comment by ilsordo** [comment]
zut

```
rm **/**~
```

**Comment by yhamoudi** [comment]
ça ne passe pas :( J'ai commit tout ce qu'il faut, tu as juste à exclure le dossier archive

**Comment by yhamoudi** [comment]
enlever aussi un fichier .dot qui est apparu à la racine
