### ISSUE TITLE
Assert_failure : tentative de double pari

### ISSUE THREAD

**Issue by yhamoudi** [ilsordo/SAT-SMT-Solver#2]
Pistes de recherche pour résoudre l'erreur "Fatal error: exception Assert_failure("formule.ml", 126, 18) " que l'on obtient par exemple en exécutant ex1.cnf
- reset_val : ajout de paris#remove v (est-ce pertinent ? déjà fait ailleurs ?)
- find_singleton : il ne faut pas que la liste contienne de variables en double (et ça peut arriver) << comment corriger ça proprement
  ...

maj : il semble que ces 2 corrections suffisent. Maintenant sur ex1.cnf ça termine et on obtient UNSATISFIABLE...

**Comment by ilsordo** [comment]
minisat dit satisfiable sur ex1, j'ai commenté un morceau de code suspicieux dans mon dernier commit

**Comment by yhamoudi** [comment]
oui la réponse est mauvaise (c'est l'ex1 du prof). Sur reset_val il manquait bien le remove ?

**Comment by ilsordo** [comment]
effectivement, tu peux commit tes modifications?

**Comment by ilsordo** [comment]
Pour find_singleton je vais le réécrire en plus simple

**Comment by yhamoudi** [comment]
j'ai des modifs à envoyer mais je doit d'abord faire un merge

**Comment by ilsordo** [comment]
Ok

**Comment by yhamoudi** [comment]
j'ai push (avec recherche naive de doublons dans find_singleton). je regarde dpll + propagation

**Comment by yhamoudi** [comment]
en fait sur ex2.cnf le pb revient...

**Comment by ilsordo** [comment]
tu as push?

**Comment by yhamoudi** [comment]
à l'instant

**Comment by ilsordo** [comment]
Ok, on verra tout ça demain.

**Comment by yhamoudi** [comment]
ah je n'ai plus le pb sur ex2.cnf :?
pour les gros tests ça envoie tjrs insatisfiable mais pour test.cnf ça marche

**Comment by yhamoudi** [comment]
Après réapparition du bug (immédiatement détruit), il y avait aussi la correction suivante à effectuer : 
dans constraint_propagation, on ne fait jamais  List.iter (fun v -> formule#reset_val v) var_prop; alors qu'il fallait le faire lorsqu'on avait "try_pari var false;" suivi de "aux()=false"
