### ISSUE TITLE
Modification de la gestion de first

### ISSUE THREAD

**Issue by yhamoudi** [ilsordo/SAT-SMT-Solver#21]
Et voilà, j'ai ajouté first dans l'état. Les modifs effectuées (cf branche first) : 
- désormais, une tranche c'est : (first,pari,propagation) avec first vrai si on peut "retourner" pari (à noter que lors du clause learning, on met par convention first=true tout le temps)
- 2 modifs mineurs dans interactions suite au changement du type etat
- j'ai abandonné le type result, maintenant : 
  - si c'est satisfiable, aux renvoie directement (Solvable paris)
  - si c'est insatisfiable, on lève une erreur : 
    - avec clause learning : on détecte Unsat dans continue_bet (tentative de poursuite d'une propagation qui génère une clause vide)
    - sans clause learning : on détecte Unsat dans undo (recherche de pièce à retourner sous le niveau 1)
- difficile de faire une fonction undo très "propre". Le choix que j'ai fait : mettre un argument à undo : None | Some k tel que : 
  - None : c'est du non clause learning, undo doit dépiler jusqu'à trouver un littéral l sur lequel changer le pari (ou Unsat). undo renvoie (Some (not l),etat)
  - Some k : c'est du clause learning, undo doit faire sauter k tranches puis renvoyer (None,etat)
- bien remarquer que undo renvoie (lors du non clause learning) le littéral sur lequel parier. 
- ces modifs ont simplifié la fonction algo (code + commun à avec/sans cl), mais complexifié un peu undo. Je ne voit pas comment enlever l'argument first de process

Je sais pas si c'est exactement ce qu'on a prévu de faire ce matin. Je trouve que l'interaction entre aux et process dans algo est plus claire mais je ne sait pas si ça simplifie la tâche pour autant. Je n'utilise plus le type "result" (il figure toujours dans algo.ml), mais je pense qu'il va rapidement revenir sous une autre forme :)

(ah oui, j'ai aussi un push qui a ajouté plein de branches mortes. je les supprimerai)

**Comment by yhamoudi** [comment]
Bon, je décrit ici le dernier push parce que ça a un peu avoir avec first.

Brièvement (c'est l'heure d'aller dormir :), j'ai fait des assez grosses modifs basées sur la remarque suivante : lorsqu'un backtrack est déclenché, on peut (et on doit) **systématiquement** déclencher derrière un continue_bet. En effet : 
- clause learning : c'est déjà claire
- conflit dans dpll avec non clause learning : ce qu'on a fait jusqu'à maintenant n'est pas formellement juste. En cas de conflit, on retournait la première variable possible. Par exemple, si on a le droit de retourner le littéral (true,3) assigné au niveau 5, on dépilait tout jusqu'au niveau 4 puis on pariait (false,3) avec **level 3 = 5** << ça c'est faux !!! En faite, 3 est devenu une conséquence de toutes les assignations effectuées jusqu'au niveau 4, donc ce qu'il faut faire c'est assigner (false,3) au **niveau 4** avec un continue bet.
- conflit dans smt : c'est assez chiant à analyser mais on peut toujours se ramener à un continue_bet. On voulait éviter cette analyse poussée (qui peut conduire à dépiler une tranche partiellement si la clause générée par smt contient plusieurs vars de niveau max), mais je n'ai pas eu d'autres choix que de la coder (code à simplifier demain...)

Une fois la prise de tête passée à coder ça (et à cacher des bugs sournois dans le code), ça simplifie pas mal run dans algo.ml : 
- la fonction de backtrack prend 3 lignes
- on dé-entrelace un peu plus process (qui perd son argument first) et bet
- on uniformise les comportements en cas de conflits
- le backtrack de smt devient "optimal"

**Comment by yhamoudi** [comment]
J'ai finit les modifs de cette aprèm et je poursuit difference_logic. Quelques remarques/questions : 
- tu parlais de "normalisation à la volée" dans parse_atom. Ca n'est pas possible avec l'algo de congruence_closure choisit, donc on garde normalize ?
- pour les piles de littéraux qu'on gère dans tous les sens. Maintenant c'est systématiquement du plus récent au plus ancien et on ne retourne qu'au moment d'appeler Smt.propagate (ça arrive à 2 endroits dans smt)
- au sujet du type etat que j'utilise actuellement dans difference_logic : je dois systématiquement recréer un état dès que je fait une modif ? Par exemple : 

```
  let init etat s1 s2 s3 = 
    let etat = {etat with graph = String_map.add s1 [] etat.graph} in
    let etat = {etat with graph = String_map.add s2 [] etat.graph} in
     {etat with graph = String_map.add s3 [] etat.graph}
```

**Comment by ilsordo** [comment]
Oui on peut garder normalize sans problème, c'est juste pour simplifier le type atom et ne pas se prendre la tête. Pour l'état c'est ça, après tu peux simplifier en "sortant" le graphe : 

``` ocaml

let g = String_map.add s1 [] etat.graph in
let g = String_map.add s2 [] etat.graph in
let g = String_map.add s3 [] etat.graph in
{ etat with graph = g }

```

Et mieux : 

``` ocaml

let g = String_map.(add s3 (add s2 (add s1 etat.graph))) in
{ etat with graph = g }
```

**Comment by yhamoudi** [comment]
bonne idée ! merci

**Comment by ilsordo** [comment]
Si un jour tu veux écrire du code Ocaml à la mode il y a un nouvel opérateur  en 4.0 : |> qui permet de faire : 

``` ocaml

let g = String_map.(etat.graph |> add s1 [] |> add s2 [] |> add s3 []) in
{ etat with graph = g }
```

**Comment by yhamoudi** [comment]
c'est joli. sinon je viens de me rendre compte que l'algo de difference logic que je comptais utiliser contient une partie plus difficile que prévu : il faut maintenir un tas min un peu particulier qui va compliquer l'implémentation...

**Comment by ilsordo** [comment]
Il n'y a pas d'alternative simple?

**Comment by yhamoudi** [comment]
il y a bellman-ford classique mais la complexité va être vraiment dégueulasse (O(mn) à chaque arête ajoutée...). Il y a aussi des bellman-ford améliorés mais qui peuvent rater certains cycles négatifs. J'essaye le meilleur algo ce soir et si c'est trop dur on avisera

**Comment by ilsordo** [comment]
Ok, essaie de dormir un peu quand même :)

**Comment by yhamoudi** [comment]
c'est bon, je peux implémenter l'algo à condition d'avoir la structure de tas min, qui n'est pas dans la lib standard... J'ai trouvé ça : 
- https://code.google.com/p/fiblib/
- http://ocaml-batteries-team.github.io/batteries-included/hdoc2/BatHeap.html et https://github.com/ocaml-batteries-team/batteries-included/blob/master/src/batHeap.ml

C'est facilement utilisable ?

**Comment by yhamoudi** [comment]
D'autres implémentations sur cette page (voir heap) : https://www.lri.fr/~filliatr/software.en.html
Le code de Braun trees me tente pas mal. Qu'est-ce que tu en penses ? je copie colle le code ?

**Comment by ilsordo** [comment]
Le premier ne m'inspire pas confiance (exception Todo qui traine mais jamais utilisée). Pour batteries c'est une bibliothèque connue, elle dépend faiblement d'autres modules mais les fonctions qui créent ces dépendances nous seront inutiles donc on peut les virer. Les Braun trees ont l'air concis, il faut peut être demander à Hirschkoff si c'est ok d'utiliser du code extérieur (Je pense que c'est honnête car la bibliothèque standard d'Ocaml est un peu ... pauvre).

**Comment by ilsordo** [comment]
Si tu copie/colle laisse bien la licence, et le jour où on le vendra il faudra réécrire :)

**Comment by yhamoudi** [comment]
le premier est le seul à implémenter les tas de fibonnacci, donc avec les meilleurs complexités, mais c'est vrai que c'est un peu une usine à gaz. 
La caractéristique principale des braun trees c'est leur extrême concision (plus que leur efficacité), je vais partir sur ça quitte à modifier la structure après

**Comment by yhamoudi** [comment]
j'ai push la première version de difference logic. Je ne pense pas avoir raté de grosses parties de l'algo, mais il y a des "détails" qui me font douter. Par exemple : si on a les contraintes k1-k2 <= c et k1-k2 <= d avec c < d par exemple (si c = d c'est le même littéral donc pas de pb). Alors, il y aura 2 littéraux différents pour représenter les 2 contraintes. Du coup je vois 3 possibilités : 
- on fait un multi-graphe et ce n'est pas un problème pour l'algo (c'est ce que je fait actuellement mais je ne suis pas convaincu que l'algo aime ça)
- l'algo doit gérer ça de manière astucieuse (je ne sais pas comment)
- ma solution préférée (mais je ne vois pas comment l'implémenter facilement) : au cours du prétraitement/normalisation on garde uniquement k1-k2 <= c (puisque d > c) ---> plus de problème de multi-arêtes, "purification" de la formule initiale.

Voilà, maintenant je peux aller dormir :)
