### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by yhamoudi** [ilsordo/SAT-SMT-Solver#22]
salut,
j'essaye de mettre en place le parser pour smt. Pour cela, je pensais définir (dans un fichier formula.ml) le type paramétré 'a formula : 

```
type 'a formula =
  | And of ('a formula)*('a formula) 
  | Or of ('a formula)*('a formula)  
  | Imp of ('a formula)*('a formula) (* implication *)
  | Equ of ('a formula)*('a formula) (* équivalence *)
  | Not of ('a formula) 
  | Atom of 'a
```

Ensuite, suivant le problème considéré, on donne un type particulier à Atom. Par exemple, pour Tseitin, je pensais juste faire la modif suivante dans tseitinFormule.ml : 

```
open Formula

type t = Formula.(string formula)
```

(dans le cas de tseitin, Atom désigne les variables).

Est-ce que cette solution te semble judicieuse ? (si oui) Je n'arrive pas à faire compiler le code en l'état, il y a "syntax error" à la ligne 3 de "tseitinFormule.ml" :( Si je place le code de "formula.ml" directement dans "tseitinFormule.ml" ça marche, mais je ne trouve pas comment corriger le pb. Tu as une idée ?

(ça se passe sur la branche parser)

**Comment by ilsordo** [comment]
J'ai cherché comment faire un parser/lexer paramétré et je n'ai pas trouvé d'exemples mais apparemment on peut encapsuler le code du parser dans un module pour en faire un foncteur.

Par contre je ne vois pas cette branche, tu l'as push?

**Comment by yhamoudi** [comment]
voilà, je pense que c'est bon

**Comment by ilsordo** [comment]
Où  est défini Formula?

**Comment by yhamoudi** [comment]
dans formula.ml (que j'avais oublié d'ajouter, il faut que tu re-pull...)

**Comment by ilsordo** [comment]
J'ai push pour cette erreur, par contre ça coince dans le lexer.

**Comment by yhamoudi** [comment]
j'essaye de corriger (c'est des warnings, il y a aussi : File "src/tseitin/tseitin.ml", line 9, characters 4-8:
Error: Unbound constructor Atom

**Comment by yhamoudi** [comment]
si je place 

```
open Formula

type t = Formula.(string formula)
```

directement dans tseitin.ml cette fois, ça passe ...

**Comment by ilsordo** [comment]
Etrange, normalement tu devrais pas avoir besoin de réécrire Formula.(...) après le open

**Comment by yhamoudi** [comment]
sans Formula.(...) effectivement, ça compile aussi (mais les warnings sont toujours là)

**Comment by ilsordo** [comment]
J'ai l'erreur dans tseitinParser, je vais essayer de faire ça avec un foncteur et je push si ça marche

**Comment by ilsordo** [comment]
C'est vraiment pas documenté donc je me lance dans de la poésie ...

**Comment by yhamoudi** [comment]
Je pense avoir réussi à faire marcher le type paramétré formula (la solution se résume principalement à ajouter open Formula dans tseitin.ml et tseitinParser.mly).

Du coup je me lance dans l'écriture du parsing et des types dont on va avoir besoin, où on essaye les foncteurs ? A priori, "Atom" devrait permettre de bien unifier tout ce qu'on peut rencontrer en SMT.

**Comment by ilsordo** [comment]
Je vais encore un peu essayer avec les foncteurs, si ils marchent on aura vraiment rien à faire pour les 2 autres smt. De toute manière le type sera le même donc on pourra tout mettre dans un module si ça marche. Sinon tu as trouvé quelque chose pour l'union find?

**Comment by yhamoudi** [comment]
je réfléchi encore sur l'union find, je n'ai rien trouvé de concluant pour l'instant :(

**Comment by ilsordo** [comment]
Ok, j'essaie de finir le squelette du smt et le parser modulaire pour demain soir.

**Comment by yhamoudi** [comment]
J'ai réussi à trouver des infos (c'était bien caché !) sur les 3 solvers de théorie à implémenter. J'ai tout mis ici : https://github.com/nagaaym/projet2/wiki/Algorithmes-de-solving

Après recherche, j'ai l'impression qu'on a 2 alternatives pour les solvers : 
- coder des algos très naifs, qui auront des perfs mauvaises mais seront facile à implémenter
- coder des algos très poussés, avec de bonnes perfs et plus difficiles à comprendre qu'à implémenter

Il n'y a pas vraiment de juste milieu parmi les algos "améliorés"... Par exemple pour congruence closure, l'algo "classique" est décrit comme incompréhensible et très difficile à implémenter (il faut travailler sur des graphes dont on maintient certaines propriétés sur les degrés), alors que le dernier algo en date est facilement implémentable...

**Comment by yhamoudi** [comment]
Les principales fonctions d'un solver : https://github.com/nagaaym/projet2/wiki/Impl%C3%A9mentation-g%C3%A9n%C3%A9rale-d'un-solveur

**Comment by ilsordo** [comment]
Génial, je vais l'implémenter selon ces grandes lignes, je pars sur l'idée que les fonctions nommées dans le document seront implémentées par chaque SMT et contrairement à ce qu'on avait dit au début ça ressemblera plus à un algo qui englobe DPLL et un SMT et leur donne la parole tour à tour.

**Comment by yhamoudi** [comment]
Il faut choisir à quel niveau on décide de propager dans la théorie (ie qui gère la période de propagation et demande à la théorie de se mettre à jour). Par exemple, si c'est fait par un algo qui englobe DPLL et un SMT, la fonction NotifyAssignment peut devenir inutile.

**Comment by ilsordo** [comment]
Je pense oui, comme ça on peut le mettre en paramètre à l’exécution.

**Comment by yhamoudi** [comment]
Des précisions sur difference logic (et surtout une tentative de description de ce que smt.init doit faire et etat_smt doit contenir) : https://github.com/nagaaym/projet2/wiki/Difference-logic

**Comment by ilsordo** [comment]
Je pense avoir un truc qui fonctionne, j'ai commencé à ramener le code vers un état compilable, c'est laborieux mais je vais de messages d'erreur en messages d'erreur et globalement rien ne bloque.

**Comment by ilsordo** [comment]
Je bloque dans le undo_clause, tu peux regarder le message d'erreur et me dire si tu vois un truc évident?

**Comment by ilsordo** [comment]
C'est bon.

**Comment by yhamoudi** [comment]
j'avais pas vu tes messages, je récupère le code et je regarde en même temps

**Comment by ilsordo** [comment]
J'ai réussi, je fais un push tout de suite, il y a une dépendance circulaire, au passage regarde le type de retour de algo.ml il est pas si moche.

**Comment by yhamoudi** [comment]
je sais pas si c'est lié à mon merge mais j'ai : 

```
Error: The files src/formule.cmi and src/interaction.cmi
       make inconsistent assumptions over interface Formule
```

je récupère la dernière version

**Comment by ilsordo** [comment]
J'ai push.

**Comment by yhamoudi** [comment]
ça va pour le type, mais pourquoi algo.mli.bak ?

**Comment by ilsordo** [comment]
Il faut que je le réécrive, je le garde comme référence. J'ai presque fini ça, après il changera de nom et algo.ml aura l'ancienne interface pour ne pas changer le code du main lié à sat et color.

**Comment by ilsordo** [comment]
Ça commence à prendre forme. Ce qui était dans algo.ml/mli est maintenant dans algo_parametric (Dpll(T))

**Comment by ilsordo** [comment]
Il ne me reste plus qu'à tout réintégrer avec le front_end. On fait un exécutable séparé pour les smt?

**Comment by yhamoudi** [comment]
il a pas mal maigri algo.ml !

Pour l'exécutable séparée : pourquoi pas, ça permet de bien distinguer smt et sat classique

**Comment by ilsordo** [comment]
Un peu oui! Par contre si on sépare il va falloir réécrire un peu de trucs, je regarde ce que je peux faire. Ta version de tseitin se trouve bien dans smt?

**Comment by yhamoudi** [comment]
le tseitin à la sauce smt ? c'est le fichier algo_tseitin.ml dans /tseitin

**Comment by ilsordo** [comment]
J'ai fini le main et corrigé plein de petites inconsistances qui s'étaient accumulées dans le code. Je suis en train de finaliser term_parser qui se plaint un peu.

**Comment by ilsordo** [comment]
Apparemment personne n'a jamais fait ça ( il y a des traces d'un truc similaire en SML, un cousin d'Ocaml ), cependant il suffit que ocamlyacc ne génère pas un fichier mli et c'est gagné! Je poursuis l'enquête.

**Comment by ilsordo** [comment]
J'ai trouvé! En fait c'est pas possible sans post-traitement avec ocamlyacc. Mais ocamlyacc est un outil obsolète, il est remplacé par menhir qui respecte à 90% la syntaxe de yacc ET permet de faire des foncteurs :)

**Comment by yhamoudi** [comment]
Il faudra bien préciser que nos lexers/parsers sont des prouesses en eux-mêmes :)

**Comment by ilsordo** [comment]
On fera un fichier Highlights.md avec les monuments remarquables de notre code :)

**Comment by yhamoudi** [comment]
Question de Patrice : comment faire un goto en OCaml ?

**Comment by ilsordo** [comment]
Est-ce une blague? Sinon il faut improviser avec des continuations.

**Comment by yhamoudi** [comment]
Non !

**Comment by ilsordo** [comment]
Dis lui de m'envoyer son code avec des commentaires là où il veut faire un goto.

**Comment by yhamoudi** [comment]
ok

**Comment by yhamoudi** [comment]
il m'a dit qu'il te montrera demain

**Comment by yhamoudi** [comment]
~~C'est quoi la fonction d'affichage de type string -> out_channel -> unit ?~~

**Comment by ilsordo** [comment]
Damned! L'erreur n'était pas que technique mais conceptuelle, j'essayais de parser dans un lexer! La solution arrive.

**Comment by ilsordo** [comment]
J'ai une solution avec menhir mais je n'arrive pas à compiler avec ocamlbuild, je vais essayer quelques hacks un peu crades ...

**Comment by yhamoudi** [comment]
j'ai regardé vite fait menhir et ça nécessite d'installer des trucs annexes. Ici : https://realworldocaml.org/v1/en/html/parsing-with-ocamllex-and-menhir.html , il y a cette commande : 

```
ocamlbuild -use-menhir -tag thread -use-ocamlfind -quiet -pkg core test.native
```

**Comment by ilsordo** [comment]
Pas besoin d'ocamlfind! (ni de core) Tu peux l'installer avec sudo apt-get install menhir, en plus il est sur les machines de l'ens.

**Comment by ilsordo** [comment]
J'en suis rendu à lire des posts insultant ocamlbuild en japonais. Je commence à considérer sérieusement la possibilité de séparer les parsers quitte à partager un lexer.

**Comment by yhamoudi** [comment]
!!! va au plus rapide. A priori, c'est la dernière étape de debug ou pas ?

**Comment by ilsordo** [comment]
A priori oui, j'essaie de court-circuiter le parsing pour que les erreurs passent plus loin.

**Comment by yhamoudi** [comment]
j'ai une première batterie de tests en stocks :)

**Comment by ilsordo** [comment]
Cool je fais un commit dans l'état actuel, est ce que tu peux écrire des parsers séparés au cas où? Le type de sortie serait atom formula_tree comme on avait fait. Je suis en train de résoudre toutes les incohérences de types qui restent.

**Comment by yhamoudi** [comment]
ok, commit. Tu as abandonné tes parsers ?

**Comment by ilsordo** [comment]
Pas abandonnés mais désactivés pour avancer. Je réessaierais dans la nuit.

**Comment by ilsordo** [comment]
Question : dans la réduction de color, toutes les variables sont Real, non?

**Comment by yhamoudi** [comment]
rappelle moi ce qu'est Real/Virtual

**Comment by ilsordo** [comment]
Dans reduction on ne stocke que les correspondances entre variables significatives et atomes (on ignore le bordel de tseitin)

**Comment by yhamoudi** [comment]
Oui, que des Real puisque pour k couleurs, on crée pour chaque sommet x les variables x_1, x_2 ... x_k tels que x_j vrai ssi x colorié en j. C'est au moment de l'affichage (si je me souviens bien) qu'on traite ces variables pour rechercher les x_k vrais (pour tout x).

De ce que je lit sur color actuel (qui n'a pas subit aucune modif), on produisait directement dans color.ml une string list list qu'on passait ensuite telle quelle au renommage (je pense).

(j'ai fait une relecture sur conflict_analysis.ml (2-3 bugs embêtants...) il y a une une zone qui me gène et pourrait expliquer le non fonctionnement de WL+théorie (hors tseitin). Je fait une relecture sur algo_parametric puis les parsers)

**Comment by ilsordo** [comment]
Ok génial, color est corrigé, config était à la ramasse, je continue d'avancer.

**Comment by yhamoudi** [comment]
ouh, t'as modification du moment où on augmente le level dans make_bet n'est pas correcte. C'est assez sournois...

**Comment by ilsordo** [comment]
J'ai des erreurs dans formule.ml ...

**Comment by yhamoudi** [comment]
ça doit venir de init

**Comment by yhamoudi** [comment]
algo_base.ml ne contient comme le mli !!!

**Comment by ilsordo** [comment]
C'est corrigé, il fallait forcer des types. L'exception Unsat est définie dans Algo_base et formule, je le laisse juste dans algo_base.

**Comment by ilsordo** [comment]
j'ai fait plein de corrections, je push

**Comment by yhamoudi** [comment]
tu parles de algo_base.ml ? en fait il y a 2 types diff entre algo_base.ml et algo_base.mli, attention à récupérer le bon fichier

**Comment by ilsordo** [comment]
Mes .mli sont enfin compatibles, je dois débugguer les .ml maintenant :)

**Comment by yhamoudi** [comment]
attend je suis perdu. Est-ce que algo_base.ml (et algo_base.mli) contiennent ce qu'il faut ? Pourquoi le type de init diffère entre les 2 ? Où est passé l'algo qui utilise continue_bet ?

**Comment by ilsordo** [comment]
euh ... attends je regarde.

**Comment by ilsordo** [comment]
Algo_base.ml/mli contiennent bien ce qu'il faut, càd la même chose, les algos sont dans algo_parametric pour ensuite être bindés dans algo.ml ou smt.ml

**Comment by ilsordo** [comment]
J'écrirais des readme dans les sous dossiers pour tout expliquer + un paragraphe dans le gros readme.

**Comment by yhamoudi** [comment]
alors le type de init doit être identique dans le .ml et le .mli ?

**Comment by ilsordo** [comment]
Je change le type d'entrée de int list list vers (bool*int) list list pour éviter de faire des opérations inutiles quand le smt passe des clauses.

**Comment by ilsordo** [comment]
Et oui effectivement, en fait je suis les erreurs de compilation pour tout corriger. Là je suis dans formule.ml/mli.

**Comment by yhamoudi** [comment]
je ne sais pas si j'ai loupé un truc mais je ne trouve aucune trace d'utilisation de continue_bet...

**Comment by ilsordo** [comment]
Effectivement ...

**Comment by yhamoudi** [comment]
\o/ (cri de peur)

**Comment by ilsordo** [comment]
C'est de la joie ou du désespoir?

**Comment by yhamoudi** [comment]
je crois que toute la partie sat a disparu (avec utilisation de undo, backtrack, make_bet...)

**Comment by yhamoudi** [comment]
un enlèvement de masse...

**Comment by yhamoudi** [comment]
en principe algo.ml contenait tout ça il y a quelque temps

**Comment by ilsordo** [comment]
algo_parametric!

**Comment by ilsordo** [comment]
Par contre continue bet n'est vraiment pas utilisé ...

**Comment by yhamoudi** [comment]
ça disparait de algo.ml lors de ton dernier commit qui affecte algo.ml le 17 mai : https://github.com/nagaaym/projet2/commit/8b0d23c4e0da876ab7527e2e12108366e9d8b7ea

**Comment by yhamoudi** [comment]
c'est immédiatement placé dans algo_parametric.ml

**Comment by yhamoudi** [comment]
ça disparait le 20 mai : https://github.com/nagaaym/projet2/commit/788b1764856cfd7188e99da192733c4e941698e0 !!! (soit hier ~~soir~~ aprèm mardi, on est mercredi...)

**Comment by ilsordo** [comment]
Oui et il est utilisé comme ça depuis. C'était pour minimiser la réécriture de vieux code.

**Comment by ilsordo** [comment]
Quoi?!!?

**Comment by yhamoudi** [comment]
dernière trace : il y a 8 heures dans algo_parametric.ml : https://github.com/nagaaym/projet2/commit/788b1764856cfd7188e99da192733c4e941698e0 (je devrais faire inspecteur)

**Comment by ilsordo** [comment]
Regarde le dernier commit que je viens de faire, il est dedans!

**Comment by ilsordo** [comment]
Et j'ai juste ajouté un espace. Pas de tour de magie.

**Comment by ilsordo** [comment]
Je sais ce qui se passe : le sat-solver est devenu conscient et il essaye de nous manipuler pour qu'on écrive skynet.

**Comment by yhamoudi** [comment]
?? je retrouve où l'utilisation de continue_bet ?

**Comment by ilsordo** [comment]
Nulle part, là il y a un problème.

**Comment by yhamoudi** [comment]
Pour moi tu as supprimé tous le corps de run dans algo_parametric.ml cette aprèm (https://github.com/nagaaym/projet2/commit/8b0d23c4e0da876ab7527e2e12108366e9d8b7ea). D'ailleurs regarde en bas de algo_parametric, c'est écrit : 

```
 let run (next_pari : Heuristic.t) cl interaction pure_prop n n cnf pure_prop in
      let etat = { tranches = []; level = 0 } in
      (prop_init, bet formule etat)
    with Unsat -> raise Unsat (* Le prétraitement à détecté un conflit, _ou_ Clause learning a levé cette erreur car formule unsat *) (***)
```

**Comment by ilsordo** [comment]
D'ailleurs une commande bien utile : 
    grep -r "texte à chercher" ./src

**Comment by ilsordo** [comment]
Euh, j'ai l'impression qu'un merge a mal tourné : pure_prop n n cnf pure_prop ???!!???

**Comment by ilsordo** [comment]
Il faut retrouver une version correcte de run et la substituer.

**Comment by yhamoudi** [comment]
en fait c'est pas il y a 8h, c'est plutôt là il y a 1h : https://github.com/nagaaym/projet2/commit/99f7bfadceb639ee9b5155e40205dec42419235a

**Comment by yhamoudi** [comment]
non, c'est bien là : https://github.com/nagaaym/projet2/commit/788b1764856cfd7188e99da192733c4e941698e0 Tu as juste couper le code en fait ?

**Comment by ilsordo** [comment]
Apparemment oui ... je restaure et je push.

**Comment by yhamoudi** [comment]
fait attention à ne pas restaurer tout le fichier

**Comment by ilsordo** [comment]
J'ai copié/collé :)

**Comment by ilsordo** [comment]
Push'd

**Comment by yhamoudi** [comment]
ok, super. Juste une question au passage, c'est correct ça (continue_bet et set_val ont tout les 2 des args opt qui s'appellent cl) : 

```
  let continue_bet (formule:Base.formule) (b,v) ?cl pure_prop etat () =
    ....
    formule#set_val b v ?cl lvl
    ......
```

**Comment by ilsordo** [comment]
oui ça passe comme il faut

**Comment by ilsordo** [comment]
Il y a un problème dans l'utilisation de continue_bet, je commit et je te l'envoie.

**Comment by yhamoudi** [comment]
je suis plongé dans tout ça. Il y a des listes qui ne devraient pas être retournées à certains endroits.

**Comment by yhamoudi** [comment]
je fait quoi ? je compile et j'étudie le problème de la ligne 180 dans algo_parametric ?

**Comment by ilsordo** [comment]
189 non? En fait continue_bet renvoie un couple (etat,propagation), je vais corriger cette ligne.

**Comment by yhamoudi** [comment]
peut-être 189 (j'ai un commit en attente). En tout cas il manque un Conflit_dpll devant la ligne incriminée : 

```
(undo_list,continue_bet formule l pure_prop etat) (***) (* on essaye de retourner la plus haute pièce possible *) 
```

Et je soupçonne le type de Conflit_dpll de ne pas être bon

**Comment by ilsordo** [comment]
C'est un peu plus subtil. Je pense qu'il faut construire une fonction qui applique continue_bet et répond comme il faut. J'ai commencé à corriger une occurence.

**Comment by yhamoudi** [comment]
si on parle bien de la même erreur, elle aurait du se produire lors du premier Bet_done (dans run) avec un renvoie de make_bet, or ce n'est pas le cas car make_bet est incorrect : il lui manque l'argument ()

**Comment by ilsordo** [comment]
non, make_bet est correct, c'est bet que l'on renvoie et qui attend ()

**Comment by yhamoudi** [comment]
ah oui, je vois. Tu as une solution ? il faut intégrer continue_bet dans quelque chose similaire à bet (et enlever l'argument unit de continue_bet)

**Comment by ilsordo** [comment]
C'est fait, je commit

**Comment by ilsordo** [comment]
cherche next, il apparait 2 fois

**Comment by ilsordo** [comment]
Je retourne typer

**Comment by yhamoudi** [comment]
je vois, je retourne inverser des listes

**Comment by ilsordo** [comment]
Question : dans backtrack je dois faire la même chose, est ce que je fais continue_bet avec ou sans cl? Vu qu'on en apprend une je devrais la mettre en argument, non?

**Comment by ilsordo** [comment]
C'est bien ça

**Comment by yhamoudi** [comment]
oui (avec cl), normalement il y est déjà

**Comment by yhamoudi** [comment]
j'ai un problème de type avec undo_clause qui ne renvoie pas d'état, se qui se répercute dans undo et devrait se répercuter plus loin. Je suis en train de corriger undo_clause pour qu'il renvoie une état

**Comment by ilsordo** [comment]
Attends je commit pour qu'on soit synchro.

**Comment by ilsordo** [comment]
C'est bon.

**Comment by ilsordo** [comment]
Fini réduction, je reviens à config. Je ne dormirais pas avant la compilation.

**Comment by yhamoudi** [comment]
il y a des trucs pas jolis dans algo_parametric. Déjà, undo_clause est vraiment pas bonne, j'essaye de la ré-écrire. Ensuite, j'ai peur qu'il y ait un problème conceptuel dans run : 
- undo renvoie un triplet (l, etat,undo_list) où undo_list est la liste des littéraux à faire sauter (nécessaire à la théorie) et l est le **premier littéral à parier**. Tu ne prenais pas l en considération (tu l'as même remplacé par un _ à un endroit) et tu renvoyais le prochain pari sur un (b,v) qui est l'agument de process. Ce n'est pas le plus grave...
- Le plus grave c'est si le continue_bet fait un raise Conflit. Qui rattrape ce conflit ?

(je commit une partie de mes corrections)

**Comment by ilsordo** [comment]
Ok je te laisse regarder et j'essaie de me débarasser de tout le reste.

**Comment by ilsordo** [comment]
Il a fallu que je remonte les structures de données dans src. J'ai corrigé une brouette de bugs, il faut que j'arrange l'histoire des atomes de difference_logic. Je vais déjà essayer de le mettre de coté et faire marcher tseitin.

**Comment by yhamoudi** [comment]
j'ai quasiment finit undo_clause. Je vais regarder cette histoire de continue_bet mais pour moi tseitin ne pourra pas marcher à cause (entre autre) de ça...

**Comment by ilsordo** [comment]
Quand je dis marcher ... c'est compiler.

**Comment by yhamoudi** [comment]
ok :) undo_clause est bon

**Comment by ilsordo** [comment]
Génial, je suis dans config, est ce que ton parametric génère des erreurs de type?

**Comment by yhamoudi** [comment]
non, j'ai debuggé

**Comment by ilsordo** [comment]
YOUPI !!1!1§1!§1§1§ ça compile :)

**Comment by yhamoudi** [comment]
push ! push !

**Comment by ilsordo** [comment]
On essaie tseitin?

**Comment by yhamoudi** [comment]
att, commentaire dans 2 s

**Comment by ilsordo** [comment]
Euh non en fait le parser lis la chaine vide ...

**Comment by ilsordo** [comment]
Il va falloir que j'aille en algo demain matin, je vais dormir à part si tu as des question sur des trucs que j'ai fait.

**Comment by yhamoudi** [comment]
j'ai besoin de ton expertise (pb avec les utilisations de continue_bet dans run qui lève des erreurs Conflit rattrapées par personne) : je propose de remplacer l'argument (b,v) de process par une application partielle de make_bet ou continue bet, qui serait exécutée 3 lignes sous "let rec process ...", à la place du make_bet : 

```
        let (etat,assignations) = make_bet formule lit true pure_prop etat in (* fait un pari et propage, lève une exception si conflit créé *) (* true = first *)
```

**Comment by ilsordo** [comment]
Je suis trop mort pour garantir quoi que ce soit mais ça n'a pas l'air incorrect donc je suis pour.

**Comment by yhamoudi** [comment]
ok, j'esseairai

**Comment by ilsordo** [comment]
Ok pas de problème.

**Comment by yhamoudi** [comment]
merci

**Comment by yhamoudi** [comment]
Voilà, c'est implémenté, je vais pouvoir dormir tranquille :)

J'ai fait disparaître toutes les fonctions next, et maintenant process prend en argument "progress" qui est : (application partielle de make_bet ou continue_bet avec tous leurs arguments **sauf** formule et etat).

 Lorsqu'on fait (progress formule etat), ça revient à lancer make_bet ou continue _bet (j'ai eu besoin de déplacer l'ordre des arguments de make_bet et continue_bet pour avoir formule et etat en tant que 2 derniers arguments).

Ça m'a l'air plus correct comme cela, mais je ne suis pas non plus 100% convaincu (autant d'applications partielles de fonctions à 3h du matin ça pique...)
