### ISSUE TITLE
Implémentation de congruence closure

### ISSUE THREAD

**Issue by yhamoudi** [ilsordo/SAT-SMT-Solver#23]
J'ouvre un fil pour suivre l'implémentation de congruence closure qui s'annonce laborieuse...

J'ai rattrapé mon pompage des braun trees en implémentant un module union-find amélioré :)

C'est la première étape au congruence closure : une structure d'union-find (tarjan) avec explications. Concrètement : étant donné 2 éléments a et b dans le même ensemble, la structure donne et décrit le nombre minimum (!) de fusions ayant conduites à placer a et b dans le même ensemble. C'est absolument indispensable dans l'algo car c'est grâce à cette structure qu'on obtient des clauses de taille min à apprendre (au lieu de prendre naïvement la négation de la conjonction de tous les littéraux assignés).

Un point intéressant sur la complexité : étant donné n éléments (au total dans l'union find) et une explication de taille k, alors l'algo la trouve en O(k*log n). Ce n'est pas dégueulasse comme complexité, mais initialement j'avais un autre algo en tête qui était en O(k) : je l'ai abandonné (temporairement ;) ) car il me faisait peur :(

J'ai également débuggé le module (en dehors du projet), il devrait être pleinement opérationnel (mais plus de tests + nettoyage du code sont encore nécessaires).

Pour la suite du jeu, ce n'est pas facile... 

Le backtrack m'embête vraiment, si tu as une idée... Il y a 2 alternatives (à mixer éventuellement) : 
- recréer les structures à chaque backtrack : la théorie doit gérer une pile de toutes les assignations depuis le début. En effet, en cas de backtrack, il faudra récupérer toutes les assignations non affectées par ce backtrack.
- stocker à intervalle régulière : quelle intervalle ? Après chaque assignation : ok mais ça coûte cher. De manière moins fréquente : alors, certains états de backtrack deviennent inaccessibles (car aucune sauvegarde faite à ce moment-là).

Enfin, sur les algos en eux-mêmes, les possibilités : 
- l'union-find précédent permet de faire totalement (et facilement !) l'égalité (sans symbole de fonctions). Et (astuce !) la procédure d'Ackermann permet de transformer toute instance de congruence closure (égalités avec fonctions) en une instance de l'égalité (sans fonctions). Du coup il y a moyen de boucler rapidement et facilement les algos, en contrepartie les complexités sont moyennes (j'ai pas plus d'infos sur la complexité pour l'instant).
- un algo d'union-find plus classique : ça peut se faire pas trop difficilement non plus, et ça devrait améliorer la complexité
- un autre super algo que j'ai sous le coude, mais pas forcément facile à implémenter

Je tenterai une implémentation quand j'aurais un backtrack.

(sinon tu t'en sors avec le debuggage général ?)

**Comment by ilsordo** [comment]
- Pour le backtrack, comme tes tas sont purement fonctionnels, je pense qu'il n'est pas absurde d'esssayer de laisser faire caml en stockant à chaque fois. Si je ne dis pas de bêtises il ne stockera qu'un pointeur et ne copiera que si c'est nécessaire. De toute manière si il y a des trous ça va tourner à la prise de tête non? Si on fait exploser la mémoire sur des petites instances on trouvera une solution.

Pour les algos on devrait faire au plus simple, après si on est vraiment en avance on peut regarder là où on est moins efficace et améliorer certains points.

Pour le debuggage je me suis pris la tête avec une référence circulaire qui venait d'un copier-coller dont le compilateur ne voulait pas me donner la cause précise, je pense avoir un exécutable propre en début d'après midi.

**Comment by yhamoudi** [comment]
J'ai une idée pour le backtrack qui permettrait de le faire pour l'union-find en temps constant et sans besoin de sauvegarder à intervalle régulière (je sais, ça vend du rêve...). J'essaye de l'implémenter et je teste si c'est ok.

**Comment by ilsordo** [comment]
Dans un premier temps je mets tout dans le même exécutable, ça permet de partager config.ml et de toute manière il n'y a pas (je crois) de subtilités de configuration des smt donc il suffit de rajouter un champ Smt à la config. Par contre je cherche un moyen d'éviter de définir toutes les combinaisons SMT/Algo à la main. Je vais tester les performances des modules en tant qu'objets de première classe.

**Comment by ilsordo** [comment]
J'ai relu le sujet et pour la congruence il demande à réutiliser l'égalité.

**Comment by yhamoudi** [comment]
pourquoi avoir besoin de définir toutes les combinaisons possibles ?

Pour la congruence closure qui s'appuie sur l'égalité, oui je l'avais en tête. Avec l'union-find actuel je pense qu'on peut dire que ce sera le cas (puisque l'égalité ne va faire qu'utiliser l'union find, et congruence closure va aussi l'utiliser plus ou moins). Maintenant, je ne pense pas qu'il voulait parler d'une réutilisation totale (avec la transformation d'ackermann par exemple qui fait que congruence closure devient exactement l'égalité).

Un point rigolo (que Tom m'avait fait remarquer) : tu peux considérer l'égalité comme un cas particulier de la logique de différences. Donc en fait tu as les dépendances suivantes : 
- congruence => égalité
- égalité => congruence
- différence => égalité
- différence => congruence

Sinon, mon union-find est capable de backtracker proprement :) (je suis encore en train de tester). Il y a un point sur lequel je n'ai pas encore de solution : lors du backtrack je ne suis pas capable de restaurer la profondeur des arbres (ce qui permet de faire de l'union sur l'arbre le plus profond). En principe, l'algo va quand même marcher mais les performances peuvent être impactées.

Une question aussi : je fait des recherches de plus petits ancêtres communs dans des arbres. Comme c'est des arbres incrémentaux, je ne peux pas vraiment faire du prétraitement pour obtenir ensuite l'info rapidement. Donc ce que je fait actuellement : 

```
LOWEST_COMMON_ANCESTER(a,b)

parents_a <- tous les ancêtres de a
tant que b n'est pas dans parents_a
  b <- parent(b)
retourner b
```

Est-ce que tu vois mieux ? Comment tu ferais l'opération de test "b est dans parents_a" ? J'utilise un List.mem pour l'instant, est-ce qu'il faut sortir la grosse artillerie pour améliorer les perfs ?

**Comment by ilsordo** [comment]
J'ai regardé un peu ton union find, ta méthode semble raisonnable, encore une fois si c'est critique en terme de performances on optimisera plus tard. Pour le moment le code est compréhensible et fort probablement correct, c'est l'essentiel.

**Comment by ilsordo** [comment]
Pour les combinaisons c'est parce que les foncteurs doivent être appliqués explicitement dans le code (module Congruence_dpll = Smt.Make_smt (Algo.Make_algo Algo_dpll) Congruence) sauf si on utilise les modules de premier ordre ( Sur lesquels je suis en train de me documenter ).

**Comment by yhamoudi** [comment]
ok, je garde des List.mem. Sinon, j'a trouvé comment restaurer la hauteur en backtrackant

**Comment by ilsordo** [comment]
Question fondamentale : quels noms pour les smt (nom concis pour les options genre -equ)

**Comment by yhamoudi** [comment]
-equ -diff -cc

-tseitin

**Comment by ilsordo** [comment]
Parfait. J'ai enfin compris comment écrire les "first class modules".

**Comment by yhamoudi** [comment]
j'ai push la version fini de l'union find avec un bon nettoyage du code depuis hier et normalement aucun bug. Seule info à retenir : lorsqu'on demande une explication, la liste de pairs (ai,bi) qu'on obtient n'est pas ordonnée (par exemple, peut-être que ai et bi ont été unis par l'appel union bi ai et non union ai bi) -> ça m'a permit de simplifier le code, mais en contrepartie il faudra faire attention à renormaliser les couples du côté de la théorie (quand elle reçoit (ai,bi), si ai<bi alors elle cherche l'atome ai=bi, sinon bi=ai).

Autres précisions : c'est robuste aux unions redondantes, ou à la demande de backtrack sur union inexistante. Par contre : impossible de défaire une autre union que la dernière effectuée (c'est normal en même temps...)

**Comment by yhamoudi** [comment]
j'ai push l'égalité : 2 théories / 3 :) Il reste les fonctions de parsing des atoms, je te les laisse si tu sais faire ça de manière concise....

**Comment by ilsordo** [comment]
Ok, j'essaie de garder un truc uniforme entre les algos mais je me rends compte que reduction est pas très bien conçu (l'histoire de la fonction d'affichage à passer). Je pense m'en sortir en sortant quelques trucs de smt. Pour les atomes je regarde.

**Comment by yhamoudi** [comment]
je fait un commit dans 2s avec une réorganisation des dossiers

**Comment by yhamoudi** [comment]
voilà j'ai un dossier theories avec les 3 théories + leurs structures de données. Il faudra aussi y ajouter tseitin (?) Peut-être qu'on peut mettre theories dans /smt

**Comment by ilsordo** [comment]
C'est pas mal comme ça, il faut juste faire attention aux tags, pour tseitin on peut ne garder que algo_tseitin.ml ?

**Comment by yhamoudi** [comment]
oui tu peux enlever le reste du dossier tseitin (jusque récupérer les fonctions d'affichage si besoin)

**Comment by yhamoudi** [comment]
pour les tags il faut juste le dossier parent ou aussi les sous-dossiers ?

**Comment by ilsordo** [comment]
Je pense qu'il faut les sous-dossiers aussi.

**Comment by yhamoudi** [comment]
c'est bon, j'ai déplacé tseitin et j'ai viré 3 sous_dossiers dans theories (vu qu'il y a qu'un seul fichier par théorie c'était pas nécessaire). De plus j'ai enlevé algo_ devant les fichiers des théories (algo_equality.ml -> equality.ml ...)

**Comment by ilsordo** [comment]
Ok, je me suis rendu compte qu'une partie des trucs que je fais avec les modules sont incompatibles avec Ocaml 3.12 ...

**Comment by ilsordo** [comment]
Est ce qu'il est toujours possible d'afficher le résultat des smt juste  à partir de la réduction ou il faut aussi l'état?

**Comment by yhamoudi** [comment]
pour la différence il faut récupérer le champ values qui contient l'opposé des valeurs à assigner à chaque ki. Pour les autres, lorsque c'est satisfiable il n'y a rien à dire

**Comment by ilsordo** [comment]
Donc des choses qui sont dans la réduction ?

**Comment by ilsordo** [comment]
Ah non ...

**Comment by yhamoudi** [comment]
Comment ça ? Pour la différence il faut values (qui est dans état) et c'est tout (même pas besoin de la réduction, il suffit de faire un iter sur values). Pour l'égalité et la congruence je ne voit pas quelles infos donner à part "satisfiable" ou "insatisfiable" et pour tseitin il faut aller chercher dans reduction (et filtrer sur les variables réelles/virtuelles)

**Comment by ilsordo** [comment]
Ok, parce que pour le moment on a pas de type de retour pour smt, j'étais donc parti sur l'idée de faire comme on avait fait pour color et tseitin : on récupère une réduction qui s'occupe de l'affichage. Ici la difficulté c'est que je ne peux pas vraiment récupérer l'état final des smt pour leur faire afficher à la fin. Je pense donc qu'il faut que les Smt renvoient du Answer.t et que Answer.t soit plus souple.

**Comment by ilsordo** [comment]
Est ce que tu peux écrire la fonction get_answer dans diff pour qu'elle corresponde à ce qui est dans  smt_base.ml ? Il faut juste afficher le modèle, il y aura déjà s Satisfiable devant)

**Comment by yhamoudi** [comment]
j'ai droit à une bool vartable maintenant dans get_answer ? c'est les assignations finales (en provenance de algo) ? Du coup pour difference j'affiche : k1 = 2, k5 = 7 par exemple, et pour les smt f(f(a))=b ... ?

**Comment by ilsordo** [comment]
Oui, normalement tu n'en as pas besoin mais il me le fallait pour tseitin.

**Comment by ilsordo** [comment]
Pour les smt sans modèles tu peux renvoyer ()

**Comment by yhamoudi** [comment]
en fait il le faut aussi pour congruence et égalité après réflexion, ça permet d'afficher les égalités effectivement satisfiables

**Comment by yhamoudi** [comment]
voilà, je pense que c'est bon. Je fait pareil sur egalité. Tu modifies les types des atomes ou je m'en charge ?

**Comment by ilsordo** [comment]
Je m'en occupe et j'écris le parser pour les atomes.

**Comment by yhamoudi** [comment]
J'ai réécrit le get_answer de tseitin et difference. Pour tseitin, je ne suis pas sur...

Sinon quel format de sortie pour différences et égalités. Pour différence je pensais à : 

```
  k1 4
  k2 6
  k3 8
```

Pour égalité/congruence : 

```
  f(a) = f(b)
  f(c) != d
```

edit : push dans 5 min

**Comment by ilsordo** [comment]
Ca me va

**Comment by yhamoudi** [comment]
j'ai push, il y avait un problème conceptuel dans les théories que je n'ai pas encore résolu dans différences (lié au fait qu'un littéral soit vrai ou pas)

**Comment by yhamoudi** [comment]
bon, ce problème est une bonne chose :) je suis en train d'extraire tout l'algo bellman-ford incrémental de equality.ml ce qui va rendre le tout bien plus compréhensible (et comme ça je peux faire un debuggage indépendant)

**Comment by ilsordo** [comment]
Cool, je finis mon anglais et je me remet sur le débuggage

**Comment by yhamoudi** [comment]
Voilà, c'est tout propre. Une fois qu'on aura la simplification des atomes ça sera encore + court (actuellement je test systématiquement que ça a bien été normalisé...).

Pour l'instant mon module bellman_ford n'a pas été mis en défaut mais c'est assez pénible à tester donc il me faut encore du temps pour être sur que tout est ok... J'ai quand même une question pour get_answer. Je voudrais que get_answer (dans equality.ml) fasse juste etat.print_values p etat (pour ne pas avoir à sortir les valeurs voulues de l'état), donc j'ai ajouté un fonction print_values dans bellman_ford.ml. Pour cela il faut une fonction d'affichage print pour le "module type Equal" situé au début de bellman_ford.ml. J'ai 3 problèmes (c'est pas des gros pbs, c'est juste que je galère avec out_channel) : 
- je ne sais pas si j'ai bien typé la fonction print dans le module Equal (tout en haut dans  bellman_ford.ml)
- comment bien utiliser cette fonction print dans print_values (tout en bas dans  bellman_ford.ml) ?
- quelle fonction d'affichage donner dans difference_logic.ml pour un affichage de string (cette fonction correspond à la fonction print du module Equal) ?

**Comment by yhamoudi** [comment]
J'ai retravaillé un peu bellman-ford + des tests et je pense que c'est bon :) J'ai aussi commencé à rédiger un readme pour le module Bellman-ford, j’essaierai de faire pareil pour union-find + des comm dans le code. J'essaye à nouveau congruence closure...

**Comment by yhamoudi** [comment]
bon c'est décidé, je me lance dans la transformation d'ackermann. J'ai vu un papier où ils le font avec des perfs pas atroces (en fait ils ont deux théories jointes : égalité et congruence, et ils ramènent tout à l'égalité)

**Comment by ilsordo** [comment]
Ok génial, je finis mon dm d'algo et j'essaie de faire compiler le bousin.

2014-05-19 20:53 GMT+02:00 yhamoudi notifications@github.com:

**Comment by ilsordo** [comment]
J'ai arrangé print_values et j'ai une solution presque élégante pour le main, plus qu'à implémenter. En bonus j'ai trouvé comment ne pas se prendre la tête avec _tags.

**Comment by yhamoudi** [comment]
super je regarde ça dès que j'ai finit de me prendre la tête avec la transformation. Je crois que je suis en train d'écrire la fonction la moins récursive terminale au monde...

**Comment by yhamoudi** [comment]
Transformation de ackermann écrite (j'ai la tête toute retournée) ! Si tu veux faire saigner tes yeux regarde le fichier congruence_closure.ml (c'est en 3 partie : transformation 1, transformation 2, transformation de ackermann).

J'ai essayer de faire le plus propre précis (le bouquet final étant la fonction ackerize2 et ses 3 fold imbriqués), mais ça va être un cauchemar à débugger.
