### ISSUE TITLE
Commit

### ISSUE THREAD

**Issue by yhamoudi** [ilsordo/SAT-SMT-Solver#24]
j'ai vu que tu as supprimé la branche smt. J'ai pas réussi à merge avec master, du coup j'ai recréée smt. Je te laisse faire le merge, puis tu peux tout envoyer...

**Comment by ilsordo** [comment]
Ok

**Comment by yhamoudi** [comment]
c'est bon, les readme sont ok

**Comment by ilsordo** [comment]
J'ai fusionné, je push et j'envoie.

**Comment by yhamoudi** [comment]
c'est tout bon, bug issues compris 

Le 2014-05-22 17:45, nagaaym a écrit : 

> Closed #24 [1]. 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [2].

## Links:

[1] https://github.com/nagaaym/projet2/issues/24
[2] https://github.com/nagaaym/projet2/issues/24#event-123872950
