### ISSUE TITLE
Renommer le dépôt

### ISSUE THREAD

**Issue by yhamoudi** [ilsordo/SAT-SMT-Solver#25]
:smiley:

Renommer `projet2` en `SAT-SMT-solver` (ou autre chose de mieux)

Et ajouter la description `A SAT and SMT solver in OCaml`

**Comment by ilsordo** [comment]
Je cherchais un truc à faire pour occuper mes vacances, je risque de réécrire des trucs pour voir si je peux le faire aller plus vite/tout casser. Et virer ces immondes objets.

**Comment by yhamoudi** [comment]
Quel courage ! On peut aussi essayer de le monnayer à un L3 (http://perso.ens-lyon.fr/daniel.hirschkoff/P2/).

Tu as mis volontairement `SMT-Solver` au lieu de `SAT-SMT-Solver` ? Je pense qu'il y a plus de gens qui savent ce qu'est un SAT solver qu'un SMT.

**Comment by ilsordo** [comment]
Corrigé.
