### ISSUE TITLE
Où sont les tests?

### ISSUE THREAD

**Issue by ilsordo** [ilsordo/SAT-SMT-Solver#4]
Je n'ai trouvé que des tests pour color dans un dossier de archive.

**Comment by yhamoudi** [comment]
Mince ils ont disparu :( pourtant je suis sur d'avoir fait un git add après regroupement des tests en sous-dossiers. 
J'ai pas accès  avant lundi à l'ordi sur lequel ce dossier doit subsister...

**Comment by ilsordo** [comment]
je vais les exhumer d'un vieux commit, j'espère ne rien casser
