### ISSUE TITLE
DLIS : assert_failure dans formule.ml

### ISSUE THREAD

**Issue by yhamoudi** [ilsordo/SAT-SMT-Solver#8]
un nouveau assert_failure :)

Cette fois-ci il est détectable en lançant dlis avec WL (avec DPLL ça marche...) sur gen2.cnf. D'après le message d'erreur, il arrive un moment où on essaye d'assigner une variable déjà assignée...

J'ai regardé ton code et il y a 2 choses qui m'embêtent : 
- ligne 105 dans heuristic.ml (à la toute toute fin), il faut bien remplacer (true,v) par (false,v) ?
- imaginons (comme pour moms précedemment) qu'il arrive un moment où l'ensemble des clauses est vide (on a réussit à les rendre toutes vraies), mais qu'il reste des variables non assignées. Comme tu parcours l'ensemble des clauses pour construire les scores uniquement sur les variables rencontrées, tu ne vas rencontrer aucune variable ! Ce qui est étrange c'est que ça devrait se traduire par un assert_failure localisé sur "assert (snd lit <> 0)" à la fin du code de dlis ! Du coup 2 possibilités : c'est bien ça le pb et l'assert failure est étrangement dans formule.ml, ou il y a un pb plus profond ailleurs dans le code :)

En fait on a codé en parallèle dlis, et j'allais push qd j'ai vu ton algo. J'ai ajouté mon code dans heuristic.ml et il faut remarquer les choses suivantes : 
- j'ai distingué dlis (sans la variante du score) et dlis_score
- pour dlis_score, j'ai besoin d'ajouter à formule.ml (et par répercussion dans formule_dpll et formule_wl aussi) une méthode get_occ qui renvoie les occurences d'une variable (ou les clauses où elle est surveillée). Dans le code envoyé, j'ai supprimé cette méthode donc dlis_score n'est plus testable en l'état.
- j'ai un peu l'approche inverse de toi : je parcours toutes les variables, et pour celles non assignées je regarde le nombre de clauses où elles apparaissent (voir même, je construit leur score). Je pense que j'évite ainsi de "rater" des variables dans le cas où toutes les clauses seraient satisfaites.
- on a la même complexité (à l'exception des 2**-C que tu calcules moins que moi)
- Ce qui est embètant avec mon dlis_score  : il faut ajouter la méthode get_occ, c'est dommage de devoir faire sortir les occurences (déjà qu'on fait sortir les clauses...). Du coup je pense qu'il faut garder ton dlis_score (une fois le bug trouvé)

**Comment by ilsordo** [comment]
C'est corrigé, comme un crétin je ne vérifiais même pas si on avait parié sur v ...

**Comment by yhamoudi** [comment]
Effectivement c'est bien ça le problème. 
Du coup j'ai pris conscience de quelque chose de plus important ! On n'avait pas le problème d'assert failure avec dpll parce que dans dpll chaque clause ne contient que des littéraux non assignés (dès qu'on assigne une variable, on la cache dans toutes les clauses où elle apparaît). C'est différent avec WL : on ne maintient pas les occurences_pos / occurences_neg (on sait juste pour chaque littéral dans quelles clauses il est surveillé). Du coup ça a pas mal de conséquences : 
- le problème qu'il y avait ici : si on regarde une clause, on peut tomber sur des variables déjà assignées
- si on regarde la taille d'une clause dans WL, c'est la taille avec toutes les variables (assignées ou non) ! En particulier, quand on observe la taille des clauses dans MOMS ou DLIS avec wl, c'est trompeur puisqu'une clause qui n'aurait que deux littéraux non assignés, mais 1000 littéraux au tout début de l'algo, va renvoyer une taille 1000 !!!

---

Je commence à me demander s'il ne faudrait pas installer les occurences_pos/neg dans WL.

Avantages : 
- on aurait les "vraies" tailles des causes
- ça permet d'implémenter exactement le dlis du prof sur wl (ou d'ajouter une nouvelle heuristique : dlis où on regarde la taille des occurences + dlis où on considère que les occurrences sont uniquement les clauses surveillées (ce qu'on fait actuellement))
- ça uniformise le comportement des clauses entre dpll et wl : dans les 2 cas un clause ne contiendrait que des variables non assignées
- on n'aurait plus à construire temporairement les occurences_pos/neg au début de WL
- qd on veut déplacer les jumelles dans une clause, actuellement on peut parcourir pas mal de littéraux faux avant d'en trouver un libre ou vrai.
- ça peut servir dans la suite des améliorations d'avoir les occurences_pos/neg

Les raisons pour lesquelles ce n'est pas déjà fait : 
- c'est une force de wl, quand une variable est assignée, de ne pas cacher dans tous les sens des clauses et des littéraux, puis de devoir rétablir tout ça quand on revient sur un pari
- ça modifie pas mal la philosophie de WL. Imaginons qu'on assigne une variable à vraie. Il faudrait alors cacher toutes les clauses devenues vraies, et enlever les jumelles présentes dans ces clauses (ça ça se fait bien). Puis dans les clauses où un littéral faux vient d'être créé, si ça supprime une jumelle ça entraîne de la propagation dans tous les sens (ça ça peut être pénible...)

Concrètement, cette modif de WL consisterait à implémenter la "possible" amélioration de wl suggérée par le prof dans ses transparents.

---

Une dernière remarque : je pense qu'il faut vraiment avoir dlis avec et sans score. Par exemple, sur n_l_k/10000_3_20000.cnf c'est 20s pour dlis sans score, 200s si on utilise le score (ceci-dit c'est du dlis avec taille des clauses "trompeuses"...)

**Comment by ilsordo** [comment]
J'ai peur que ça diminue l'avantage de wl mais on peut essayer de ramener les occ_pos occ_neg.

Qu'est ce que tu entends par dlis sans score?

**Comment by yhamoudi** [comment]
le dlis sans score c'est parier sur le littéral "qui rend le plus de clauses satisfaites". Dans le score (c'est écrit "variante" dans les diapos), on combine nombre de clauses vraies et longueur de ces clauses. Longueur des clauses c'est trompeur pour WL, donc il faudrait aussi avoir le DLIS qui pari sur le littéral qui est surveillé dans le plus de clauses.

Je réfléchis encore à la modif de WL et éventuellement je ferais les modifs pour comparer les performances.

**Comment by ilsordo** [comment]
Ok, au pire on peut garder les 2 versions de wl côte à côte et si celle qu'on a actuellement pose vraiment des problèmes il suffira de remonter tout ce qui à rapport aux occurences dans formule.ml

**Comment by yhamoudi** [comment]
Je n'ai pas lancé les grosses modifs sur WL. Si on regarde toutes les propagations à mener, ça devient quasiment du DPLL (et je n'ai trouvé aucun papier qui évoque de telles propagations). Je garde sous la main les remarques sur les modifs possibles, et on verra par la suite...

Par contre je pense qu'il y a un vrai problème avec les heuristiques actuelles moms et dlis sur WL puisque la notion de "taille des clauses" est biaisée. Déjà sur du 3-SAT, on peut remarquer que DPLL+DLIS est plus puissant que WL+DLIS (alors que WL a une grande avance sans heuristique).
WL+MOMS reflète le plus le problème actuel. Il est très mauvais sur du 3-SAT (presque au niveau de WL seul), et surtout, à partir du moment où toutes les clauses ont la même taille (ce que fait notre générateur) c'est inutile de regarder leur taille ! En fait, MOMS+WL actuel pari juste sur le littéral le plus fréquent : c'est exactement l'heuristique dlis (sans le score) décrite par le prof (sauf qu'ici on augmente la complexité en mesurant les tailles et en créant le clauseset "elements").

Du coup, voilà ce que je propose (et que j'ai mis en place :) : 
- dans formule_wl.ml et formule_dpll.ml, j'ai ajouté une méthode clause_current_size qui donne le nb de vars non assignées dans une clause donnée. 
- grâce à cette méthode, on obtient le vrai moms sur WL
- pour dlis, j'ai ajouté l'heuristique sans score : pour DPLL on pari sur le littéral qui rend le + de clauses satisfaites, pour WL celui qui est surveillé dans le plus d'endroits. La complexité est assez bonne et il y a des bons résultats expérimentalement.
- j'ai repris ton heuristique dlis et je l'ai légèrement modifiée. Déjà, je l'ai renommée **JEWA** (son vrai nom c'est "Jeroslow-Wang Heuristics"). Ensuite, je calcule le score avec la bonne taille des clauses.

J'ai aussi trouvé ce document assez intéressant : http://www.cs.wm.edu/~idillig/cs780-02/matthew-pirocchi.pdf Il contient plein d'heuristiques. Quelques-unes intéressantes : 
- **DLCS** : trouver la variable (et non littéral) la plus fréquente, puis parier sur sa polarité la plus fréquente >> très simple à implémenter et il parait qu'elle est plus rapide que jewa. Du coup j'ai pas pu résister et je l'ai implémentée :) (mais on l'enlève si elle est mauvaise ou si elle n'apporte rien par rapport aux autres heuristiques)
- VSID : pas forcèment facile à mettre en place mais très intéressante (apparement c'est ce qui est utilisé dans minisat). De ce que j'ai lu ailleurs, ça s'implémente plus facilement lorsqu'on a l'apprentissage de clauses
- ...
